### PR TITLE
CAT-2009 Media Library background URL based on screen orientation

### PR DESCRIPTION
**Pull request by cheidenreich**

### CODE REVIEW

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
test this please

**Comment by cheidenreich** [comment]
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidTriggerPullRequestTest/1507/

**Pull request merged**
