### PR TITLE
CAT-2211 Backbutton now gets displayed on Sub-PreferenceScreens

### PR DESCRIPTION
**Pull request by AntiDog**

### CODE REVIEW

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please fix checkstyle issues

**Comment by AntiDog** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by cheidenreich** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by cheidenreich** [comment]
This does not appear to fix the root cause of the problem but attaches some quickfix-code with deprecated methods

**Comment by AntiDog** [comment]
well as far as I can tell the root cause of the problem is that the preference screens are made by nesting preference screens within the XML. This is the cleanest solution I found for this since apparently to my understanding it is intended behaviour that sub preference screens don't show the back button, at least that's what I understood when reading [this](https://stackoverflow.com/questions/16374820/action-bar-home-button-not-functional-with-nested-preferencescreen) and following the linked https://issuetracker.google.com/issues/36910297

So how should I proceed on this?

**Pull request closed without merging**
