### PR TITLE
 CAT-1678 Update LegoEV3Impl.java, moveMotorSpeed

### PR DESCRIPTION
**Pull request by axel-wild**
Old type was SHORT. But speed may be given from -100 to 100.

### CODE REVIEW

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
has this been tested with the lego hardware?

**Comment by axel-wild** [comment]
Yes, I tested it with a LEGO EV3.
In EV3Command the parameter `data` results in

`byteToAppend = EV3CommandByte.EV3CommandParamFormat.PARAM_FORMAT_SHORT.getByte()
                    | EV3CommandByte.EV3CommandParamByteCode.PARAM_TYPE_CONSTANT.getByte()
                    | (EV3CommandByte.EV3CommandParamByteCode.PARAM_SHORT_MAX.getByte() & data);`

but `EV3CommandByte.EV3CommandParamByteCode.PARAM_SHORT_MAX` is `0x1F`.
So speed 31(dec) results to 0.
Maybe `EV3CommandByte.EV3CommandParamByteCode.PARAM_SHORT_MAX` should be `0xFF`?
I don't think so, because I did not find any usages with parameter values greater than 13.
(Found in `LegoEV3Impl.playTone(...`
`command.append(EV3CommandParamFormat.PARAM_FORMAT_SHORT, volumeLevel);` 
Axel

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
i cannot answer your questions, please try to clarify them and let me know if this should be merged or not.
also the jira ticket 1678 doesnt seem to have anything todo with this.

is there a jira ticket for this issue?

**Comment by cheidenreich** [comment]
closing this for now, too many uncertanties

**Comment by 84n4n4** [comment]
correct ticket id is:
https://jira.catrob.at/browse/CAT-1417

**Pull request closed without merging**
