### PR TITLE
CAT-2618 Language reset to device language on restart

### PR DESCRIPTION
**Pull request by ndrnour**
add the new supported Languages.
fix the problem with change language on API >= 25

### CODE REVIEW

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
last time i saw a testrun actually starting there were two unit tests broken due to this.

**Comment by ndrnour** [comment]
UtilFileSizeTranslationsTest.java & UtilFileTest.java , not any more browken.

**Comment by 84n4n4** [comment]
test this please

**Pull request merged**
