### PR TITLE
CATROID-613 TouchAndSlideBrick

### PR DESCRIPTION
**Pull request by Koell**
add a new Touch Brick that lets you define start/stop coordinates to the touch action
this brick simulates a touch and drag movement with a finger
adjusted testTapAtMultitouch.catrobat to be more stable

https://jira.catrob.at/browse/CATROID-613

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by trummerp — CHANGES_REQUESTED** [review]
Hi, good work !

I think you don't need the two constructors in the TouchAndSlideBrick class.
Please check that. If you remove them, you can also remove empty parentheses in the class declaration `class TouchAndSlideBrick()`.

**Review by trummerp — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Please resolve the merge conflict, and also please use the following default values for the brick:

> Touch and slide 
> from x: -100 y: -200 
> to x: 100 y: 200
> in 0.3 seconds

**Comment by wslany** [comment]
The testTouchAndSlide.catrobat test has dependencies on running times that are device dependant, and thus could make them flaky on slow devices (like our emulators...): It is not ensured that clones are placed where they should. Aso, loops may be come much faster in the future (see https://jira.catrob.at/browse/CAT-2440 ). Maybe you could use some synchronization flag or counter to indicate that the clone was successfully placed, and wait for it in the background script before creating the next clone? Or, more elegantly and probably slightly faster, change the coordinates on the block object's side?

**Review by qlin93 — APPROVED** [review]
Requested changes were made. Looks good.

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
