### PR TITLE
CAT-2009 MediaLibrary contains different backgrounds

### PR DESCRIPTION
**Pull request by StefanBuerscher**
for landscape and portrait mode programs

### CODE REVIEW

**Comment by StefanBuerscher** [comment]
Is it necessary to create constants for "Portrait" and "Landscape"?

**Comment by thmq** [comment]
Please fix the Checkstyle warnings. Constants should not be necessary in this case.

**Comment by robertpainsi** [comment]
Oh, I forgot to click `Comment` to comment on this PR a few days back. :joy_cat:

The Web team also works on the problem and will provide a server side fix. [WEB-304](https://jira.catrob.at/browse/WEB-304) Major and HighPriority. I suggest to wait for their fix and adapt [CAT-2009](https://jira.catrob.at/browse/CAT-2009) accordingly.

**Comment by thmq** [comment]
As suggested by @robertpainsi we will wait for the changes at the server side.

**Pull request closed without merging**
