### PR TITLE
CAT-1254 Checkstyle

### PR DESCRIPTION
**Pull request by robertpainsi**
Jira-Ticket: https://jira.catrob.at/browse/CAT-1254
This PR is open for discussion only and therefore shouldn't be merged at the moment. Since I'm the person who also created the tickets, other opinions are welcomed and highly appreciated. Also all checks can be fine-tuned to increase code quality.

Every check can be inspected on it's own and the corresponding commit has a link to the jira ticket and the checkstyle check.

Special thanks to @X4mp for implementing the checkstyle rules.
https://github.com/Catrobat/Catroid/pull/1203 has been closed because it's easier for me to handle the PR if I'm the owner of the branch. The PR contained information why we dropped the AvoidStaticImport check. Thanks to @aried3r for the professional feedback.

Whitespace and similar checks will be added later. https://jira.catrob.at/browse/CAT-1321

Also take a look at https://jira.catrob.at/browse/CAT-1277 and drop some comments about naming conventions.

### CODE REVIEW

**Comment by robertpainsi** [comment]
> CAT-1257 Add checkstyle rule ExplicitInitialization

Should we use that?

\+ Removes inconsistency, code cluttering, and redundancy.
\- There are cases, an explicit initialization is more readable

Also discussed here http://stackoverflow.com/questions/19939118/why-are-explicit-initiallizations-of-the-default-value-bad

**Comment by avihric** [comment]
review pls @thmq @obusher @SimonStefan @aried3r

**Comment by obusher** [comment]
@avihric Looks good! 

@robertpainsi 
* `ExplicitInitialization` rule is ok for me. 
* Which rule replaces the `LicenseHeaderTest` ?
* The commit from #1249 is also in this PR.

**Comment by robertpainsi** [comment]
I will create sub-tickets for each of the unlabeled (and poor) commit messages and reword them. I just pushed them for inspection purposes because this should be in the develop branch before other PR are merged. Hopefully in the next few days :smirk_cat:

> ExplicitInitialization rule is ok for me.

Lets postpone the decision if we use it. There are other checks in this PR which should be merged asap and also this check can be introduced in a few seconds https://jira.catrob.at/browse/CAT-1257?focusedCommentId=16211

> Which rule replaces the LicenseHeaderTest ?

Thanks for the hint, I updated the commit message. https://github.com/robertpainsi/Catroid/commit/7c06a4de932671147ab375aff0c3c65d3fa2d99d

> The commit from #1249 is also in this PR.

Good catch! However, this is on purpose. There are some checks and properties which aren't available in the previous version. We have to merge https://github.com/Catrobat/Catroid/pull/1249 first, then I update this branch again.

**Comment by obusher** [comment]
Just FYI:

`21:48:05 :compileDebugTestJava/home/catroid/jenkins_slave3_no_device/workspace/Catroid-Build-SourceTests-StaticChecks/catroidTest/src/org/catrobat/catroid/test/ProjectManagerTest.java:70: error: exception CompatibilityProjectException has already been caught`

**Comment by robertpainsi** [comment]
I :eyes:
```git rebase```, why do you do this to me? ^^

**Comment by obusher** [comment]
The `CompatibilityProjectException ` still gets thrown.

**Comment by robertpainsi** [comment]
> The CompatibilityProjectException still gets thrown.

Interesting. There seems to be a problem with jenkins in this case. I rerun the branch with the same hash as above 140ab899ba066bb64c53c5afad757f039100aafb and it's green ^^ [GreenJenkins build](https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Build-SourceTests-StaticChecks/2643)

> edit: Please rebase your branch.

:+1: Thanks for merging! :kissing_cat:

**Comment by obusher** [comment]
ok to test

**Comment by robertpainsi** [comment]
I was using the canary channel version of AS and had to install the stable version to test the codeStyleSettings.xml settings. Now it suites the stable version :wink:

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
* `org.catrobat.catroid.uitest.ui.activity.MyProjectsActivityTest.testCopyCurrentProject` is [ green.](https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-Device-Single-ClassAndPackage-Test/301/) 
* `org.catrobat.catroid.uitest.content.brick.SetLookBrickTest.testAddNewLook` is a known issue [(CAT-1438)](https://jira.catrob.at/browse/CAT-1438)

**Pull request merged**
