### PR TITLE
CAT-2673 none sense error message while registration

### PR DESCRIPTION
**Pull request by ndrnour**
* removing unused Strings
* Sets an error message that will be displayed below the TextInputLayouts
(Username/E-mail/Password/confirm Password ) instead of showing AlertDialogs
* Check E-mail and Username availability in background
* Username should start with Latin character or number and contains no "@" - to block using email as username
* Check if the the provided Email_address matches Patterns.EMAIL_ADDRESS
* Password should be at least 6 characters
* Check if Password and Confirm Password are matched

### CODE REVIEW

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by thmq** [comment]
you don't have to run espresso tests separately anymore with the arrival of the glorious `continuous-integration/jenkins/pr-merge` :wink:, it does all the fancy magic for you.

**Comment by thmq** [comment]
Nice work :+1: I really like that you used proper callbacks through the listener and removed unnecessary utility methods (such as `showDialog`). and :+1: for the nice description in the comment here.

I'll leave it open till tomorrow (@84n4n4 might want to say anything about testing), if nothing comes up, I'll merge it then.

**Comment by LPeteR90** [comment]
Will be part of hotfix 0.9.36, merged into develop from there

**Pull request closed without merging**
