### PR TITLE
CATROID-176 IfOnEdgeBounce and Steps with Physics Objects

### PR DESCRIPTION
**Pull request by maxf24**
Physics Objects did only bounce due to physical collisions, not due to steps taken explicitly.

- Physics Objects touching the edge of the screen by steps taken now also bounce off and travel in the opposite direction.
- Physics Objects using the Left-Right rotation-style are now correctly flipped when set to look left on start.

As discussed with @wslany only "testIfOnEdgeBouncePhysicsMoveStepsRegression.catrobat" is needed for the Acceptance Criteria found on Jira. 

JIRA: https://jira.catrob.at/browse/CATROID-176

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by trummerp** [comment]
Hi, good work! 
There are some things i came across while testing:

- If bouncing on the **left or right edge**, the object's flip seems to be depending on the starting angle. 
E.g.: I added a starting angle of 10° to [https://share.catrob.at/pocketcode/program/79684](url) and what happened was that
the object always reflecting with a degree of 0°+-(10°) or -180°+-(10°).
- Also the gravity seems a little strange. Depending on the angle (I tested it with 45°) at which the object hits the edge, it seems to accelerate or slow down and never really stops flying through the space(screen). I guess it is expected, that sooner or later the object should be held on the ground by gravity (At least that is what i expect about gravity:D)

**Comment by maxf24** [comment]
Hi!

_If bouncing on the left or right edge, the object's flip seems to be depending on the starting angle._
This is intentional as it's the same behaviour as a non physic object that touches the wall with steps and an specific angle.

 _it seems to accelerate or slow down and never really stops flying through the space(screen)_
If an object is flying up with steps and normal gravity is pulling it down, it starts to fall when the velocity > steps/min. When touching the ground the velocity is much greater then we think it is because the steps slowed it down before, therefore bouncing much harder as one would think. 
The problem here is that steps and the physics environment work very differently and do not mix well.

**Review by Koell — APPROVED** [review]
👍

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
