### PR TITLE
CATROID-880 Formula editor buttons for list and text functions, reorderings, and renamings

### PR DESCRIPTION
**Pull request by atharva137**
Formula editor buttons for list and text functions, reorderings, and renamings 

https://jira.catrob.at/browse/CATROID-880

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by atharva137** [comment]
Hi @Walcho1125  sir,

Please review, resolved last comment  i.e. 
 a new function(CATROID-926) was recently merged into develop which was related to your ticket. Therefore it would be necessary to add the sensor to the sensor category and the text function directly under "color at x y" and in the logic category at a suitable position just as it is explained at the end of (CATROID-926)

Attached Screenshot for the same 

formula_editor_keyborad
Mathematics
Properties
List
Logic
Text

**Review by Walcho1125 — CHANGES_REQUESTED** [review]
Hello,
I closed the previous PR. However, please take a look at our [Commit Message Guidelines](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines) and 
[How to create a PR](https://github.com/Catrobat/Catroid/wiki/Creating-a-pull-request) and change everything accordingly.

**Comment by atharva137** [comment]
Hello Sir,
I have made changes according to our  Commit Message Guidelines and
How to create a PR 

Please review it 
Thanks and Regards 
Atharv

**Review by Walcho1125 — CHANGES_REQUESTED** [review]
Hello, 
thank you, please rename your commit starting with CATROID-880 and move the "color equal color with % tolerance( 'ff0000' , 'fe0000' , 1 )" to the "comparison operators" since this action is no logical operator. Keep in mind to squash your commits to one single, other than that it looks good. 
Best regards

**Comment by atharva137** [comment]
@Walcho1125 
Hello sir 
I have made all the changes as requested 
please review it 
Thanks and Regards
Atharva

**Review by Walcho1125 — CHANGES_REQUESTED** [review]
Hello! 
Please squash your commits again! everything else is ok! 
Best Regards

**Pull request closed without merging**
