### PR TITLE
CATROID-1392 CLT for look name and number of looks

### PR DESCRIPTION
**Pull request by l-ilma**
Implementation of the CLT as part of the training ticket: https://jira.catrob.at/browse/CATROID-1392
Test checks whether each of the looks name is correct and if there is a correct number of looks at the end.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by Walcho1125 — APPROVED** [review]
Looks good

**Review by wslany — CHANGES_REQUESTED** [review]
Hi @l-ilma thank you for the test! It is nice, but I would like to ask you to :pray: remove the Wait brick in the script (see screenshot). Reason is that all our tests already run for a very long time, and the CLT run sequentially. Each little saved time the tests run faster is time developers have to wait less until their test runs complete. 
image

**Comment by l-ilma** [comment]
> Hi @l-ilma thank you for the test! It is nice, but I would like to ask you to 🙏 remove the Wait brick in the script (see screenshot). Reason is that all our tests already run for a very long time, and the CLT run sequentially. Each little saved time the tests run faster is time developers have to wait less until their test runs complete. image

Hi @wslany, I understand :) I've removed the wait brick now.

**Comment by wslany** [comment]
Thanks, @l-ilma . However, for some reason the code.xml seems to be corrupted. On https://developer.catrobat.org/Catblocks/develop/ I get this error: 
```Error: The file could not be loaded. Maybe you passed an invalid .catrobat/.zip file.```

When I rename and try to unzip the .catrobat file, WinRAR responds with a diagnostic message saying that the code.xml file is corrupted.

Above never happened before with .catrobat files in the past.

I tried with Catroid, and there it works fine, that is why the test also passes on Jenkins.

Please, could you try to export the file once more from Catroid and replace the file in the PR? Please also download it from the PR and check with https://developer.catrobat.org/Catblocks/develop/ whether it then works fine.

:pray: Please could you export the file again and

**Comment by l-ilma** [comment]
> Thanks, @l-ilma . However, for some reason the code.xml seems to be corrupted. On https://developer.catrobat.org/Catblocks/develop/ I get this error: `Error: The file could not be loaded. Maybe you passed an invalid .catrobat/.zip file.`
> 
> When I rename and try to unzip the .catrobat file, WinRAR responds with a diagnostic message saying that the code.xml file is corrupted.
> 
> Above never happened before with .catrobat files in the past. Do you may have some explanation why this could have happened?
> 
> I tried with Catroid, and there it works fine, that is why the test also passes on Jenkins.
> 
> 🙏 Please, could you try to export the file once more from Catroid and replace the file in the PR? Please then download it from this PR and check with https://developer.catrobat.org/Catblocks/develop/ whether it works fine.

Hi @wslany. I exported the project again and checked it in https://developer.catrobat.org/Catblocks/develop -> it renders just fine now so I hope it is OK.
I really don't know why the issue happened in the first place. When I exported the project for the first time, there already was a file with the same name in the device storage so I just replaced the existing one. Could this possibly be the cause of the problem?

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks! Maybe it was once of those [bit flippings due to cosmic radiation... (it's real)](https://youtu.be/lTaBwPe988I).

**Pull request merged**
