### PR TITLE
[Refactoring] Replaced lists with RecyclerViews, a lot of stability fixes:

### PR DESCRIPTION
**Pull request by thmq**
- Changed cloning behaviour for Bricks, LookDatas, SoundInfos. (shallow vs. deep copies.)
- Refactored storage handling.
- Refactored Backpack handling -> tried to move wacky code into segregated places.
- and lots more ... (also removed unnecessary tests).

### CODE REVIEW

**Comment by thmq** [comment]
DO NOT MERGE yet. I will add tests and squash commits. but feel free to test it.

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Comment by thmq** [comment]
please run espresso tests

**Pull request merged**
