### PR TITLE
CAT-1742 usability improvements

### PR DESCRIPTION
**Pull request by p4p4**
rebased & reopened #1872 (use release-branch as base).

this contains minor UX improvements (string changes, radiobutton style, etc), nothing fancy

ping @thmq: please accept it if you want to add it to the new release. Otherwise you can close it.

### CODE REVIEW

**Comment by robertpainsi** [comment]
Just a note that the base branch was `Catrobat:release-0.9.27`

**Comment by thmq** [comment]
oh! that's not good ...

**Comment by robertpainsi** [comment]
I just created PR https://github.com/Catrobat/Catroid/pull/2042 which has `develop` as base.
The `release-0.9.27` branch can be deleted. (btw, [the base of a PR can be changed](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request))

**Comment by thmq** [comment]
I know, however, for some reason I seem to be unable to change the base.

**Pull request merged**
