### PR TITLE
CATROID-1110 Fixed the "Finish stage" heading by removing "match_parent"

### PR DESCRIPTION
**Pull request by sahil9001**
property from brick layout tag

*Please enter a short description of your pull request and add a reference to the Jira ticket.*
Reference: https://jira.catrob.at/browse/CATROID-1110

This PR fixes the UI bug when `Backpack` was selected from the overflow menu. Fixed it by removing the `match_parent` from the `BrickLayout` tag as it was taking up the whole width and height of the parent leaving no space for the text to show up. Like the other similar tags, I found out across the codebase that the tag is removed to show the correct text.
### Before :
Before
### After: 
After

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by sahil9001** [comment]
@wslany

**Review by wslany — COMMENTED** [review]
Hi @sahil9001 thanks a lot for spotting this and finding a solution for it. One question: What about the changes in .idea/compiler.xml, are they needed for this pull request?

**Comment by sahil9001** [comment]
@wslany Yeah, I think that change is unnecessary too! but I don't know how to remove that file, can you tell me ho to do so?

**Review by wslany — APPROVED** [review]
Thanks!

**Comment by wslany** [comment]
Note: Simple fix, so I merged it immediately, bypassing the normal review process.

**Pull request merged**
