### PR TITLE
CAT-1161: Added ceil and floor functions to formula editor along with tests

### PR DESCRIPTION
**Pull request by KKcorps**
Here are the screenshots of the same:

screenshot_2015-01-20-20-13-58
screenshot_2015-01-20-20-14-32
screenshot_2015-01-20-20-14-46

### CODE REVIEW

**Comment by KKcorps** [comment]
Please merge this or give reviews..

**Comment by avihric** [comment]
Currently we are not merging any PRs due to our instable master branch. We are working hard to get it stable again. Therfore pls have some patience.
Don't worry your PR will be reviewed sooner or later.
Regards.

**Comment by KKcorps** [comment]
Has the master branch been stabilized yet?

**Comment by avihric** [comment]
Hi, unfortunately not. We are almost there. Have some more patience. Also consider that we all are volunteer students, so we have other duties as well.
Thank you for your understanding.
Regards.

**Comment by KKcorps** [comment]
Hey I am a student too.So if you want I can help you guys with that.Although I am still a beginner but with your help, I think, I'll be able to contribute.

**Comment by linsm** [comment]
please reopen your pull request

use your forked repository
target of pull request should be 'develop' branch
link THIS pull request in the new one

**Pull request closed without merging**
