### PR TITLE
Test if Jenkins static source code works

### PR DESCRIPTION
**Pull request by robertpainsi**
Just a test...

### CODE REVIEW

**Comment by robertpainsi** [comment]
ok to test

**Comment by robertpainsi** [comment]
ok to test

**Comment by robertpainsi** [comment]
ok to test

**Comment by thmq** [comment]
should I add you to the admin list on Jenkins so that you can actually trigger PR tests?

**Comment by robertpainsi** [comment]
> should I add you to the admin list on Jenkins so that you can actually trigger PR tests?

:smile_cat: Nah! Was just interested why https://github.com/Catrobat/Catroid/pull/1598#discussion_r58293609 shows a green build...
Also just found out I don't need to open a Pull Request to test it. But currently, the [check doesn't seem to work](https://jenkins.catrob.at/job/CatroidCheck/53/).

However, cool to see that jenkins is reanimated step by step! :+1:

**Comment by thmq** [comment]
check should work, however there are still some issues regarding the emulator's stability and besides there have been some network issues all day. I'll still add to the admin list ;) you do not get admin privileges on the Jenkins it merely enables you to trigger test.

**Comment by robertpainsi** [comment]
> I'll still add to the admin list ;) you do not get admin privileges on the Jenkins it merely enables you to trigger test.

Alrighty then!

**Comment by robertpainsi** [comment]
ok to test

**Comment by robertpainsi** [comment]
ok to test

**Comment by robertpainsi** [comment]
ok to test

**Comment by thmq** [comment]
@robertpainsi do you still need this PR? If yes, please just reopen.

**Comment by robertpainsi** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Pull request closed without merging**
