### PR TITLE
CATROID-386 Add notes and credits section

### PR DESCRIPTION
**Pull request by dandrawes**
https://jira.catrob.at/browse/CATROID-386
Edit and view notes and credits in "Show details" screen
Add notes and credits section when uploading

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by mstoeg — CHANGES_REQUESTED** [review]
Looks good! According to the ticket specification the Catroweb API should already support adding the "Notes and Credits", so I am wondering why the TextField in the Web UI is still empty after adding "Notes and Credits" during the upload project process.

**Comment by dandrawes** [comment]
> Screenshot from 2020-10-15 07-41-20
> Looks good! According to the ticket specification the Catroweb API should already support adding the "Notes and Credits", so I am wondering why the TextField in the Web UI is still empty after adding "Notes and Credits" during the upload project process.

Catrobweb does not support showing the "Notes and Credits" yet.

**Review by mstoeg — APPROVED** [review]
Well done!

**Comment by mstoeg** [comment]
> > Screenshot from 2020-10-15 07-41-20
> > Looks good! According to the ticket specification the Catroweb API should already support adding the "Notes and Credits", so I am wondering why the TextField in the Web UI is still empty after adding "Notes and Credits" during the upload project process.
> 
> Catrobweb does not support showing the "Notes and Credits" yet.

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
