### PR TITLE
CATROID-467 Fixed Correct English  Capitalisation

### PR DESCRIPTION
**Pull request by Darshpreet2000**
CATROID-467 Correct English Capiatlisation
Fix Bug CATROID-467

**BEFORE**

Screenshot_2020-02-22-17-20-46-24_5e2641223565f6d4087fbf5fe12dc97f

**AFTER**
Screenshot_2020-02-22-17-33-55-65_cb8aa1fae54ae6bf52051e5ffd7b0259

### CODE REVIEW

**Comment by Darshpreet2000** [comment]
I was not able to open that link but still I added description

**Comment by Darshpreet2000** [comment]
catrobat

**Comment by PlantinumX** [comment]
[KNOWHOW-CommitMessageGuidelines-260220-1340-79.pdf](https://github.com/Catrobat/Catroid/files/4255733/KNOWHOW-CommitMessageGuidelines-260220-1340-79.pdf)

pls have a look on this pdf

**Comment by Darshpreet2000** [comment]
Now correct?

**Comment by PlantinumX** [comment]
DeepinScreenshot_select-area_20190827124303
pls change commit message.

**Comment by PlantinumX** [comment]
DeepinScreenshot_select-area_20200226180213
pls change commit message.

1) git commit --amend
2) this message should be taken  -> CATROID-467 Fixed Correct English Capitalisation
3) git push -f origin CorrectEnglish

**Comment by Darshpreet2000** [comment]
Now Correct?

**Comment by Darshpreet2000** [comment]
Please merge this

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
