### PR TITLE
CAT-1326

### PR DESCRIPTION
**Pull request by thomasmauerhofer**
Change LookController to fix Bug with loading an image from the storage.

### CODE REVIEW

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
`Caused by: java.lang.NullPointerException
at org.catrobat.catroid.ui.controller.LookController.loadImageIntoCatroid(LookController.java:301) 
at org.catrobat.catroid.ui.fragment.LookFragment.onActivityResult(LookFragment.java:410)
at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:166)
at org.catrobat.catroid.ui.ScriptActivity.onActivityResult(ScriptActivity.java:292)
at android.app.Activity.dispatchActivityResult(Activity.java:5322)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
 	... 11 more`

**Comment by thomasmauerhofer** [comment]
Current TestRun: https://jenkins.catrob.at/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1700/

**Pull request merged**
