### PR TITLE
CATROID-680 & CATROID-682

### PR DESCRIPTION
**Pull request by ndrnour**
this pr contains the implementation of both tickets, cause they are related to each other.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by ndrnour** [comment]
note #3731 needs to be merged beforehand.
still missing `Together with this ticket, the feature toggle for the listening brick shall be removed and the feature made available for all users.` to avoid rebasing and fixing conflicts afterward, I'll implement the missing part once the mentioned PR #3731 got merged.

**Comment by ndrnour** [comment]
### **please feel free to review the code! **

**Review by dardiv — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
The sensor works fine, but when I tried to set the language to Deutsch (Deutschland) (sensor correctly reports de_DE), the speech that is recognized is French instead of German. When I set the language to francais (France), again the sensor is correctly set to fr_FR, but the speech recognizer understands only some other language (not sure, maybe Spanish or Portuguese or some other language from that family). Maybe an index problem?

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!!!

**Pull request merged**
