### PR TITLE
CATROID-504 Fix Lost changes due to reloading of projects

### PR DESCRIPTION
**Pull request by Pratik1999**
Ticket :- [https://jira.catrob.at/projects/CATROID/issues/CATROID-504](url)

The Bug was Caused due to Reloading of Current Project in ProjectUploadActivity, When the project is reloaded the project variable is assigned a new reference, whereas the other variables like currentlyEditedScene, etc still refer to the old project reference Scene. So when the ProjectUploadActivity finishes and the ProjectActivity and corresponding fragments resume the variable doesn't point to correct reference.

The ProjectUploadActivity has been modified to not load the projects when it is already loaded(which is the case when the ProjectUploadActivity is launched from ProjectActivity)

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by wslany** [comment]
PRAISE: Thanks!

PLEASE FIX: This PR should have 1, 2, or 3 commits only: 
1. Refactorings commit, if any. This should be separate so that reviewing is easier, since the refactoring may be easier to understand if it is not mixed with the rest of the pull request. It also helps if you specify which refactoring pattern you used and why. For details, see for instance https://refactoring.guru/refactoring/catalog - Note that this commit is optional if there are no refactorings, or only very minor ones.
2. Tests only commit, if any new ones. Run the pull request once on jenkins with only these one or two first commits, without the third one: your new test(s) must _fail_. This is so that reviewers can check that the tests actually detect the bug (in case of new features, some structural code without logic may also already have to be included to allow writing the test cases), and to remind you that we do Test-First development. Also, it makes reviewing simpler since code or PO reviewers can concentrate only on the test logic. This commit is optional if there are no new tests, but remember that we normally absolutely _need_ tests, either regression tests for bug fixes, or normal unit tests, UI tests, and/or system integration tests because of our Test Driven Development approach. 
3. Production code commit, either bug fix or new feature implementation. Again, separating it from the other commits makes it easier for the reviewers, thus usually speeding up the review process.

**Comment by wslany** [comment]
Thanks! Please let me know when your PR is ready for a code review.

**Comment by Pratik1999** [comment]
Can you please have a look, and let me know if any further changes are needed

**Comment by wslany** [comment]
Build #7 has the failing test, in #8 everything is green: very nicely done. Thank you! 

Would you be available to do the code review synchronously together with the code reviewer? That usually speeds up the resolution of any problems tremendously, and get's the code merged much  faster. Please let me know.

**Comment by Pratik1999** [comment]
No problem in that, I will be available during the code review.

**Pull request closed without merging**
