### PR TITLE
CAT-1838 Separated events from other control bricks

### PR DESCRIPTION
**Pull request by bernadettespieler**
UX got the apk for testing

### CODE REVIEW

**Comment by thmq** [comment]
ok to test

**Comment by bernadettespieler** [comment]
ok to test

**Comment by bernadettespieler** [comment]
ok to test

**Comment by bernadettespieler** [comment]
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/197/

**Comment by robertpainsi** [comment]
Please remove file `git show HEAD~2`

**Comment by thmq** [comment]
you have got 3 commits, please squash them and rebase with develop in order to make it merge-able. reopen when done.

**Pull request closed without merging**
