### PR TITLE
Revert "Merge pull request #1167 from kaufi/CAT-1243"

### PR DESCRIPTION
**Pull request by robertpainsi**
This reverts commit 16b4452f666d5d2fdbc270020b657736275f2876, reversing
changes made to c3d64ecc548956ec8e8056a4386b5c4c114f14bb.

Reverts https://github.com/Catrobat/Catroid/pull/1167

### CODE REVIEW

**Comment by kaufi** [comment]
any problems on the previous pullrequest?

**Comment by robertpainsi** [comment]
The src test may have failed also in the previous commit in AS 0.9.8. But the unit and ui tests should run.

In AS 1.1 the unit tests fail immediately.

I newly cloned and imported the project into a fresh AS 1.1 installation. The folder structure displayed by AS changed. Also there is no cucumber project and maybe other projects are missing too.

I'll provide more information when I'm on the train riding home. ;)

**Comment by robertpainsi** [comment]
Ohh, maybe I just need to change the view from Android to Project in the upper left corner. All projects and other stuff is there. *do'h*

Now the unit tests start. I still have to test it with a device and internet connection. Atm I get a exception in the storagehandler with the emulator. But that's not important atm.

**Comment by kaufi** [comment]
The jenkins build after the merge has finished with "just" one error: https://jenkins.catrob.at/view/All-Categories/view/Experimental/job/Catroid-Multi-Job-Master-RELOADED/284/

the pullrequesttest before merging was successful too - but I'll check it on my notebook with a fresh installation of AS and a fresh clone of the repository as well :)

**Comment by robertpainsi** [comment]
Internet connection + device -> unit and uitests are running smoothly. :+1:
But the source tests are still failing :crying_cat_face:

**Comment by robertpainsi** [comment]
> but I'll check it on my notebook with a fresh installation of AS and a fresh clone of the repository as well :)

No need to check it... I tested it again and it works. Can't explain why it didn't before :worried:

Thanks a lot for your support! :smile_cat:

**Pull request closed without merging**
