### PR TITLE
CAT-FIX No Activity Found To Handle Intent

### PR DESCRIPTION
**Pull request by nishantt95**
No activity found to handle an archive package in WebViewActivity.java

Crashlytics URL: http://crashes.to/s/81b37a8aeeb

Firebase URL:
https://console.firebase.google.com/u/0/project/firebase-catrobat/monitoring/app/android:org.catrobat.catroid/cluster/e1e17603

### CODE REVIEW

**Comment by robertpainsi** [comment]
Please let me know how to reproduce this error :flushed:

**Comment by nishantt95** [comment]
I tried to produce this error but it worked fine. 😿

**Comment by robertpainsi** [comment]
This seems to be a problem in apk generated apps. I'll forward this PR for review.

**Comment by nishantt95** [comment]
Ok

**Comment by cheidenreich** [comment]
test this please

**Comment by 84n4n4** [comment]
-- This seems to be a problem in apk generated apps. I'll forward this PR for review.

if this is true, we should investigate why apk generated programs want to call that in the first place and fixing that.
closed also on behalf of cheidenreich

**Pull request closed without merging**
