### PR TITLE
CATROID-705 RegEx Catrobat Language Test

### PR DESCRIPTION
**Pull request by david-loe**
https://jira.catrob.at/browse/CATROID-705

CATROID-705 RegEx Catrobat Language Test

- ADD Regular Expression Function Test

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by elsner91 — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
"When scene starts" scripts are run more or less as _parallel_ threads. A single "Finish stage" exits the stage for _all_ scripts, i.e., as soon as the first "Finish stage" is executed, _all_ other running scripts are aborted. Therefore, the current way you did it does not make sure that all Assert bricks can be executed. Please change it to make the execution deterministic. 
image

**Comment by wslany** [comment]
Also, please add test cases for MULTILINE, DOTALL, the (?i) and (?ui) prefixes, and how to match the beginning and the end of an input using \A and \Z.

**Comment by wslany** [comment]
Regarding the race condition I mentioned in my previous request for changes above, regarding the multiple "Finish tests" bricks, please do _not_ use one "Wait until all other scripts have stopped" before the single "Finish tests" brick to synchronize the execution of all scripts, since this creates another race condition on very slow emulators where one cannot be sure whether _all_ parallel scripts have already started when the single "Wait until all other scripts have stopped" followed by the "Finish tests" brick are executed.

A better way is to have only _one_ script, possibly with "Note __" bricks in between the sections to separate them visually. In the parameter field of the "Note __" bricks, you could also put a short explanation, though it is not really necessary.

**Comment by david-loe** [comment]
All requested changes have been implemented

**Review by artjom404 — APPROVED** [review]
Looks fine to me.

**Review by wslany — CHANGES_REQUESTED** [review]
Please do not leave 'Kommentar hier hinzufügen…' as a comment text in the note bricks. Please replace it by a meaningful note or an empty string. 

What is the added value of the 4th testing pair?
image

Please only English:
image

DOTALL is set by default (that's what the test should document / specify), so no (?s) needed in the DOTALL test:
image

Same for MULTILINE: it is set by default (that's what the test should document / specify), so no (?m) needed in the MULTILINE test: 
image

**Comment by david-loe** [comment]
1. Added a description to every test block
2. test block #4 is a consequence of the separation of lower and uppercase letters, it tests for a sequence of uppercase letters
3. deleted unnecessary flags

**Review by elsner91 — APPROVED** [review]

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
