### PR TITLE
CATROID-1046 Touch area to enter project from main page is too small

### PR DESCRIPTION
**Pull request by dandrawes**
https://jira.catrob.at/browse/CATROID-1046

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by mstoeg — APPROVED** [review]
Well done!

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks!

But now, when I tap on the Upload button on the main screen, then, when I am on the login dialog page, I tap the back button, I then _incorrectly_ stay on the login page instead of coming back to the main page. If I then tap on the back button again, it exits the app. Before, it behaved correctly, so it must be due to this fix.

Also, why no test for the new behavior? Even better would be test *first*. Reasons are: maintenance documentation, and safety against regression bugs. Please also add a test for above incorrect behavior, and please try to develop it in a test-first manner.

**Comment by wslany** [comment]
Just retried with mit https://jenkins.catrob.at/job/Catroid/job/PR-4132/2/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-4132-2.apk an a 
* Samsung Galaxy Note 20 Ultra with Android 10 with the same result: first tap on back button => stays on login screen; second tap => exits app
* Samsung J7 with Android 6.0: again, same result.
* Google Pixel 5 with Android 11: the app is already closed after a single tap on the back button.

**Comment by wslany** [comment]
Note: A rebase has "fixed" the apparent bug.

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
