### PR TITLE
CATROID-301 "Single tap at x: y:" brick for Catrobat language tests

### PR DESCRIPTION
**Pull request by 84n4n4**

### CODE REVIEW

**Comment by wslany** [comment]
In Catroid/catroid/src/androidTest/assets/catrobatTestRunnerTests/success/testTapBrick.catrobat, if one adds a script that places the objectToBeTapped at the coordinates x=500, y=0 and changes the tap coordinates in the Background to the same coordinates x=500, y=0, the test incorrectly *fails*:

image

image

image

**Comment by 84n4n4** [comment]
been a problem with the coordinates. i played around with it now, and it works now.

**Comment by 84n4n4** [comment]
modified test to prevent this from reaccuring

**Comment by wslany** [comment]
Further thoughts need to be invested in the way this brick is defined and implemented. As it is defined now, it does not reflect the way the word "Tap" is used in the "When tapped" and "When stage is tapped" bricks, and also not how a tap is defined on https://developer.android.com/studio/debug/dev-options under "Input".

**Comment by wslany** [comment]
Thanks!!!!!!!!

**Pull request merged**
