### PR TITLE
CATROID-1069 REFACTOR CloneAction to Kotlin

### PR DESCRIPTION
**Pull request by Aayush2111**
Jira ticket: https://jira.catrob.at/browse/CATROID-1069

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Aayush2111** [comment]
@ThorstenBandel @sebastiangollob 
Please review the changes and provide any feedback that you may have.
Thank you! :)

**Review by sebastiangollob — CHANGES_REQUESTED** [review]
Please also ensure that the files have up-to-date copyright notice using the builtin format feature of Android Studio (e.g. CloneAction.kt is missing the 2023 in the copyright notice).

**Comment by Aayush2111** [comment]
> Please also ensure that the files have up-to-date copyright notice using the builtin format feature of Android Studio (e.g. CloneAction.kt is missing the 2023 in the copyright notice).
> 
> See also #4693

Updated on both
Thanks! :)

**Review by mseiser — APPROVED** [review]
thank you!

**Review by sebastiangollob — APPROVED** [review]
lgtm. Thanks!

**Pull request merged**
