### PR TITLE
CATROID-801 Added language test for Add to List at Position

### PR DESCRIPTION
**Pull request by petbuer**
Added a new language test for the Add to List at Position brick.
JIRA: https://jira.catrob.at/browse/CATROID-801

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by Koell — CHANGES_REQUESTED** [review]
The catrobat test seems to be corrupt as I can't import it with Catroid or with the Catblocks-Renderer. The Catroid version you used might have been bugged. Please look into it and reupload the file.
A possible way to test if there are no problems is with the Catlbocks-Renderer: https://developer.catrobat.org/Catblocks/develop/

**Review by Koell — APPROVED** [review]
👍  looks good

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks. 

However, this test does not only contain tests with negative numbers but also with positive numbers. Also, it does not test the Add to list brick, but instead the Insert into list brick. Please rename the test accordingly from testAddListAtNegativePosition.catrobat to testInsertIntoList.catrobat

Please also test with non-integer values such as 1.4, 'abc', and sqrt(-1) (which is equal to 'NaN'). 

The test with -5 is not needed, since there's already one with -10. It is the same test. Please remove one.

**Review by Koell — APPROVED** [review]
:+1: requested changes were made

**Review by wslany — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks! We are almost there: Please just delete the spurious Test list that is apparently not used anywhere, and also the ugly "X"-like automatic screenshot.

**Review by Koell — APPROVED** [review]
last requested changes were made

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
