### PR TITLE
CATROID-183 Add visual placement to ShowVariable bricks

### PR DESCRIPTION
**Pull request by mstoeg**
- Refactor VisualPlacementActivity (split complicated onCreate() method into multiple methods)
- Convert text to bitmap in order to handle it as ImageView
- Create Utils class for displaying texts - otherwise it would have been necessary to call stage methods from UI context

Further notes:
- If no variable (new...) is selected in the spinner of the ShowVariable brick the visual placement option is not visible. (as this is not further specified in the ticket)
- Always the values of the variables from the last run are shown, as it is already the case for many other fields

https://jira.catrob.at/browse/CATROID-183

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by BeinhAlex — APPROVED** [review]
Very good!

**Review by wslany — COMMENTED** [review]
@mstoeg It seems that https://jenkins.catrob.at/job/Catroid/job/PR-3811/23/testReport/org.catrobat.catroid.uiespresso.intents.visualplacement/SpriteActivityVisualPlacementTest/All___2___Pull_Request_Suite___testNotInterpretableInput/ at https://github.com/Catrobat/Catroid/blob/develop/catroid/src/androidTest/java/org/catrobat/catroid/uiespresso/intents/visualplacement/SpriteActivityVisualPlacementTest.java#L141 fails persistently. Can you please check whether this could be related to this PR, since that's a visual placement UI test?

**Comment by mstoeg** [comment]
Thank you @wslany - I fixed the test that you pointed out. The error was quite obvious as the VisualPlacement-Option should not be displayed when the input is not interpretable. Nevertheless the faulty testcase was not introduced with this PR as this one must have been failing for a long time.

**Comment by wslany** [comment]
> Thank you @wslany - I fixed the test that you pointed out. The error was quite obvious as the VisualPlacement-Option should not be displayed when the input is not interpretable. Nevertheless the faulty testcase was not introduced with this PR as this one must have been failing for a long time.

Hmm, it hasn't failed till now, see, e.g., https://jenkins.catrob.at/job/Catroid/job/develop/424/testReport/org.catrobat.catroid.uiespresso.intents.visualplacement/SpriteActivityVisualPlacementTest/ 

Anyway, thanks for fixing it!!

**Pull request merged**
