### PR TITLE
CAT-1161: Added ceil and floor functions to formula editor along with tests

### PR DESCRIPTION
**Pull request by KKcorps**
Hi,
Here is the PR for the develop branch.Please review it and merge the same.
[Link to previous PR] (https://github.com/Catrobat/Catroid/pull/1189#issue)

### CODE REVIEW

**Comment by obusher** [comment]
Please rebase onto `Catrobat:develop` and [squash](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i) your commits into a single one.

**Comment by avihric** [comment]
Please remove the changes in catroid/res/values-de/strings.xml, as only the english strings.xml is needed from now on.

**Comment by KKcorps** [comment]
Sure.Has it failed because of this or is there any other reason?

**Comment by avihric** [comment]
No the reason is that other PRs have been merged in the meanwhile, especially #1194

**Comment by obusher** [comment]
@KKcorps : Please rebase onto `Catrobat:develop` and [squash](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i) your commits into a single one. :large_orange_diamond:

**Pull request closed without merging**
