### PR TITLE
CATROID-839 Human pose detection sensors

### PR DESCRIPTION
**Pull request by qlin93**
https://jira.catrob.at/browse/CATROID-839

Updated Google ML Kit versions in build.gradle
Added Google Pose detection to FaceAndTextDetector.kt and renamed it to FaceTextPoseDetector.kt
Refactored face and text detection to make it more readable.

Automated testing is not yet possible for this feature. 
Manual testing of pose in comibination with face and text detection was done on a OnePlus N10 and a Xiaomi Mi Mix 2.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by petbuer — APPROVED** [review]

**Comment by wslany** [comment]
Hi, please fix the lint warnings on Jenkins and rebase. Thanks!

**Comment by qlin93** [comment]
@wslany Done. 👍

**Comment by wslany** [comment]
Thanks. I think the increase the Catrobat language number in https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/common/Constants.java#L45 was lost due to the rebase you did 20 minutes ago, I guess?

**Comment by qlin93** [comment]
@wslany Yes it did, sorry about that. I updated it again.

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
