### PR TITLE
CATROID-835 "Empty" event brick

### PR DESCRIPTION
**Pull request by Rawbat**
Implemented the brick as a grayed out brick(like if it was commented out). Also removed the option to comment it out or in.

https://jira.catrob.at/browse/CATROID-835

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by adnaribo — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
As this is a new brick, please increase the Catrobat language version number in the constants.

Also, in the "Event" category of bricks where the user can select one of the event bricks, this new empty brick shall _**not**_ be listed. The brick does not have to be available there, as it only is _automatically_ added when the Catblocks 2D view is used to separate a few bricks from an normal event header brick, and then dropped at a place without connecting them to another script. I.e., don't show the empty event brick at the bottom of the menu where the event bricks are selected. Everything else can stay the same.

Please also change the second year in the year-to-year range in all touched files to 2021, for instance here:
image

**Review by adnaribo — CHANGES_REQUESTED** [review]

**Review by adnaribo — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Please add 
- a test of the brick's functionality (that bricks below it are *not* executed) with a CLT

- an espresso test that:
1. the brick is _not_ visible in the event category
2. a script with the "Empty" event brick _is_ visible in the scripts
3. there's _no_ text on the event brick.

**Comment by wslany** [comment]
Also, please remove the lint warning.

**Review by adnaribo — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks! Please update the CLT, I'm sending the new version via slack since github does not allow .catrobat attachments.

**Comment by wslany** [comment]
New version details for @adnaribo: more readable error message, and longer delay to ensure that the success is not due to a slow emulator:
image

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
