### PR TITLE
CAT-1608 CAT-1609 CAT-1610 singletouch and multitouch

### PR DESCRIPTION
**Pull request by p4p4**
reopened https://github.com/Catrobat/Catroid/pull/1745 after rebase
Code review done - ready to merge.

___________

Implemented CAT-1608 CAT-1609 and CAT-1610 (Single and Multi-Touch), which are sub-tasks of CAT-1601

When screen is touched:

    is a new head brick
    executed whenever the screen is touched

Single Touch description:

    screen_touch_x and screen_touch_y return the coordinates of the last touch
    screen_is_touched returns 1 when the last touch on the display is still active

Multi Touch description:

    screen_touch_x ( i ), screen_touch_y ( i ), screen_is_touched ( i ) parametrized
    index i is 1 for the first touch and increases after each new touch, until the project is restarted
    last_screen_touch_index returns the index of the last touch
    screen_touch_x ( i ) und screen_touch_y ( i ) preserve there values, even when screen_is_touched ( i ) is false again.

test-program:
https://dl.dropboxusercontent.com/u/961915/catroid-multitouch/multitouch%20test%20neu.zip

### CODE REVIEW

**Comment by p4p4** [comment]
out of curiosity - is there a better way to reopen a closed pull request instead of just creating a new one? Unfortunately I can't see a button to reopen it again. 

Always creating a new pull request is tedious and also decreases clarity due to the increasing amount of pull requests.

IMO leaving a pull request open to allow me to rebase should suffice. I'm just saying.

**Comment by thmq** [comment]
Normally you should be able to reopen a closed PR via a simple button click. However, I've heard that there have been issues with this. I'll look into it.

**Comment by p4p4** [comment]
thank you for merging, @thmq :)

**Comment by thmq** [comment]
about the issue with reopening PRs: 

> We're blocking the pull request reopen if the current head isn't a descendant of the stored head sha (which is what the head was when the pull request was closed). We are not allowing the reopen in that case, because there is no good way to tell what changes have happened while a pull request was closed and the head branch has changed.

this is GitHub's answer to the issue. So apparently you cannot reopen a PR after you have force pushed anything onto it.

**Comment by robertpainsi** [comment]
> So apparently you cannot reopen a PR after you have force pushed anything onto it.

With [this little trick (How to reopen a pull-request after a force-push?)](https://confluence.catrob.at/pages/viewpage.action?pageId=9666894) you easily can, if you have the rights to reopen pull requests.

> Normally you should be able to reopen a closed PR via a simple button click.

The problem seems to be that developer with read access can't reopen pull requests at all. Even if they didn't force push. See https://github.com/Catrobat/Catroid/pull/1719#issuecomment-224739814

**Pull request merged**
