### PR TITLE
CATROID-554 Dialog Box is made to show variables(complete)

### PR DESCRIPTION
**Pull request by Bhavya-22**
https://jira.catrob.at/browse/CATROID-554
DialogBox is made to show the complete values of variable(name as well as value) acces by a right arrow updated in Data category.
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Bhavya-22** [comment]
@wslany please review it and let me know if I need to change something

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks! Please resolve the lint warnings, see https://jenkins.catrob.at/job/Catroid/job/PR-4006/1/analysis/

Also, the build is failing, see https://jenkins.catrob.at/job/Catroid/job/PR-4006/1/execution/node/54/log/
```
18:13:40  > Task :catroid:compileStandaloneDebugJavaWithJavac
18:13:40  /home/catroid/jenkins_slave/workspace/Catroid_PR-4006/catroid/src/main/java/org/catrobat/catroid/ui/recyclerview/adapter/UserDataRVAdapter.java:44: error: cannot find symbol
18:13:40  import org.catrobat.paintroid.MainActivity;
18:13:40                               ^
18:13:40    symbol:   class MainActivity
18:13:40    location: package org.catrobat.paintroid
18:13:41  Note: Some input files use or override a deprecated API.
18:13:41  Note: Recompile with -Xlint:deprecation for details.
18:13:41  Note: Some input files use unchecked or unsafe operations.
18:13:41  Note: Recompile with -Xlint:unchecked for details.
18:13:41  1 error
18:13:41  
18:13:41  > Task :catroid:compileStandaloneDebugJavaWithJavac FAILED
18:13:41  
18:13:41  FAILURE: Build failed with an exception.
18:13:41  
18:13:41  * What went wrong:
18:13:41  Execution failed for task ':catroid:compileStandaloneDebugJavaWithJavac'.
18:13:41  > Compilation failed; see the compiler error output for details.
```

**Comment by Bhavya-22** [comment]
@wslany  Sir I have corrected all the lint warnings except drawable-nodpi which is showing in lint warning but i am unable to find it in my local files. So, please let me know what should I do about that also I am working on the issues so that build should not fail and I will write a test regarding this also.
Sir is there any way by which I can check whether jenkins is allowing my files or some error is still there.
If there is a way than please let me know.

**Comment by Bhavya-22** [comment]
Sir also can you please guide me on  how to write a test regarding this so that it would run without any issues.
 I also need help to know how to solve build issues.
Please guide me regarding the same.

Thank you in advance and Regards

**Comment by Bhavya-22** [comment]
@wslany sir, I have committed the changes as specified by Jenkins, but sir, there are 4 lint warnings about strings but that I have not added, so should I remove it or let it be as it is. (Because they are unused resources).

**Comment by Bhavya-22** [comment]
@wslany Sir, I have added UI test for the arrow(in data fragment), which on click shows dialog by the name-FormulaEditorShowVariableTest.

Now sir, from my side, all the changes you requested and errors because of my contribution to Jenkins are solved (except new lint warnings/error if any for test file). Kindly review it and let me know if any further changes are required.

**Comment by khushal1707** [comment]
@Bhavya-22 Please squash all the commits to a single commit, resolve lint warning https://jenkins.catrob.at/job/Catroid/job/PR-4006/10/analysis/, and rebase this PR.

**Comment by Bhavya-22** [comment]
Yes sir I will definitely squash all my commits into one basically just waiting for the approval for my contribution.
And sir regarding lint warning the 4 strings values in which lint warning is showing is not added by me.(They are unused resources) so should I just remove them or use tools:ignore for them.

Please let me know about this .
For  remaining checkstyle, I will check and improve it accordingly

**Comment by khushal1707** [comment]
> Yes sir I will definitely squash all my commits into one basically just waiting for the approval for my contribution.
> And sir regarding lint warning the 4 strings values in which lint warning is showing is not added by me.(They are unused resources) so should I just remove them or use tools:ignore for them.
> 
> Please let me know about this .
> For remaining checkstyle, I will check and improve it accordingly

Rebasing might solve this issue.

**Review by wslany — CHANGES_REQUESTED** [review]
Hi, thanks a lot, and sorry for the delay!

I just executed it with this brick 
image

and then inspected the variable list 
image
There is a big empty area that would be better used to show the content. What do you think?

When I tapped on the arrow this was shown:
image
However, this is not necessary, as we have the "edit" option on long-press:
image

So, the arrow is not needed (it will be replaced by a context menu with three vertical dots via https://jira.catrob.at/browse/CATROID-501 ) as the content can already be shown via the edit menu item:
image

Please 🙏 continue working on a more compact visualization of the overview over the variables and list content. That would be very helpful to have. The detail view is not necessary. Best regards and thank you.

**Comment by Bhavya-22** [comment]
Sir I also checked in my device regarding the same but I also execute this block for Catrobat.org then receive this.

From the below screenshot it is specifying that if we view long scrollable value in dialog then it starts from the starting point but when I see it in edit text so it start from middle point so I need to just scroll up to get to top and see and then start the whole scrolling process to view it.

Also one more issue to see such big value in edit text is if by mistake any alphabet/button/touched then whole value will get replace and then it's going to be quite irritating to start the whole process.

So after seeing your also I think for now I can put arrow not along with text but below it and to the end . Or if you permit I can try expandable text view concept for the same.

**Comment by Bhavya-22** [comment]
On my screen it is showing like this.
Now as you seen this problem. Firstly, sorry about it. And secondly I will run it on different devices using emulator and improve it so that the empty space can be occupied.
On your device it is not occupying because of the constraints as it is prefering to put the next word in next line instead of on the same line.(Maybe due to less spacing) But on mine it got enough space to put next word on same line yet there are some space that can be occupied (or maybe left intentionally to provide spacing between text and arrow). But I will try on different device then work on the improvement for this.
Sorry for the trouble again.

**Comment by wslany** [comment]
Thanks!

> So after seeing your also I think for now I can put arrow not along with text but below it and to the end . Or if you permit I can try expandable text view concept for the same.

🙏 please leave the arrow away, it is not necessary anymore. Also, there is no need for the view of the content of a single variable in a popup as shown by your PR when I tap on the arrow, so please do not include that. It is solved by another way.

Please concentrate only on the overview of all variable values.

Also, on your screenshot there is the same empty space on the right. In your case it is only a bit smaller because the variable name you used is longer and thus takes more space on the left:
image

Please try with a single character name for the variable, such as in my screenshot "x", and then it will probably look the same.

**Comment by Bhavya-22** [comment]
Sir I tried different methods and one method which I think is looking good is the attached screenshot.

**Comment by wslany** [comment]
@Bhavya-22 this looks good indeed, thanks a lot!

**Comment by Bhavya-22** [comment]
So sir, should I close this PR and just commit this change as this change is done by doing changes in layout only

**Comment by wslany** [comment]
> So sir, should I close this PR and just commit this change as this change is done by doing changes in layout only

🙏 Yes please.

**Pull request closed without merging**
