### PR TITLE
CAT-1740 Refactored FormulaEditor Layout

### PR DESCRIPTION
**Pull request by StefanBuerscher**

### CODE REVIEW

**Comment by thmq** [comment]
ok to test

**Comment by cheidenreich** [comment]
not sure about the exact goals of this ticket --> see JIRA for details

**Comment by bernadettespieler** [comment]
The children had problems to tap on the buttons because they are too small on tablets. This solves the problem!
The font size is another step which will be coverd with https://jira.catrob.at/browse/CAT-1984

**Comment by cheidenreich** [comment]
okay, thanks for clearing that ;)

**Pull request merged**
