### PR TITLE
CATROID-693 removed drone implementation

### PR DESCRIPTION
**Pull request by maxf24**
Changes from #3839 

+ keep formula elements
+ deleted not used functionality in `CatroidApplication.java`

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by adnaribo — CHANGES_REQUESTED** [review]
please resolve conflicts :)

**Comment by wslany** [comment]
Why are the apks still of the same size if the drone libs have been removed?

Also, have @ndrnour 's comments from https://github.com/Catrobat/Catroid/pull/3839#issuecomment-715092465 and https://github.com/Catrobat/Catroid/pull/3793#pullrequestreview-510871068 been addressed?

**Comment by maxf24** [comment]
> 
> 
> Why are the apks still of the same size if the drone libs have been removed?
> 
> Also, have @ndrnour 's comments from [#3839 (comment)](https://github.com/Catrobat/Catroid/pull/3839#issuecomment-715092465) and [#3793 (review)](https://github.com/Catrobat/Catroid/pull/3793#pullrequestreview-510871068) been addressed?

**Comment by maxf24** [comment]
> 
> 
> Why are the apks still of the same size if the drone libs have been removed?
> 
> Also, have @ndrnour 's comments from [#3839 (comment)](https://github.com/Catrobat/Catroid/pull/3839#issuecomment-715092465) and [#3793 (review)](https://github.com/Catrobat/Catroid/pull/3793#pullrequestreview-510871068) been addressed?

I unfortunatly dont know.
Yes, this has been addressed.

**Review by wslany — CHANGES_REQUESTED** [review]
Please also delete https://github.com/Catrobat/Catroid/blob/develop/catroid/PARROT_License_JUNE_2011_v2_1.txt

Deleting the following lines should make the apk file size smaller I hope:
https://github.com/Catrobat/Catroid/blob/564bc4f624a365834a4f53ba49e8ea5896679bcd/catroid/build.gradle#L367-L369

There are a few other lines in the same file that might not be needed anymore, look for parrot, e.g. (there are more):
https://github.com/Catrobat/Catroid/blob/564bc4f624a365834a4f53ba49e8ea5896679bcd/catroid/build.gradle#L209

The following lines shouldn't be needed anymore:
https://github.com/Catrobat/Catroid/blob/49ba63b52ccf7af97817a1c060e6c8a9fe88c0a1/catroid/config/lint-baseline.xml#L169-L179

On the other hand, the following lines probably are still needed since the bricks still exist:
https://github.com/Catrobat/Catroid/blob/49ba63b52ccf7af97817a1c060e6c8a9fe88c0a1/catroid/config/lint-baseline.xml#L1003-L1090

The following lines should not be needed anymore:
https://github.com/Catrobat/Catroid/blob/b097a5cd7672ba34541461135e5a053a7fbe7b05/catroid/src/main/AndroidManifest.xml#L50-L57

Also not needed anymore:
https://github.com/Catrobat/Catroid/blob/b097a5cd7672ba34541461135e5a053a7fbe7b05/catroid/src/main/AndroidManifest.xml#L242

I'm not sure, but are these lines still needed:?
https://github.com/Catrobat/Catroid/blob/b097a5cd7672ba34541461135e5a053a7fbe7b05/catroid/src/main/java/org/catrobat/catroid/CatroidApplication.java#L49-L52

Please also review once more the commits for the drone in the past, we may have missed other things. Good starting link might be https://github.com/Catrobat/Catroid/commits?author=wagnergerald&before=656b244655338b083031473939464adc6e14590c+35

**Comment by wslany** [comment]
=> #4107

**Pull request closed without merging**
