### PR TITLE
CAT-1856 Added tagging dialog

### PR DESCRIPTION
**Pull request by LauraBebek**

### CODE REVIEW

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
retest this please

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Comment by fwinkelbauer** [comment]
Please fix the format issues - read more [here](https://github.com/Catrobat/Catroid/wiki/Creating-a-pull-request)

**Comment by fwinkelbauer** [comment]
please fix conflicts and reopen when done

**Pull request closed without merging**
