### PR TITLE
[Accessibility] Refactored Data Fragment

### PR DESCRIPTION
**Pull request by thmq**

### CODE REVIEW

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by robertpainsi** [comment]
Access `i` bility maybe?

**Comment by thmq** [comment]
please run espresso test

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Pull request merged**
