### PR TITLE
CAT-2178

### PR DESCRIPTION
**Pull request by Chypsylon**

### CODE REVIEW

**Comment by robertpainsi** [comment]
Rebasing will :sparkles:magically:sparkles: remove all merge commits. :smile_cat:

**Comment by thmq** [comment]
Rebasing will also ⭐️ effectively ⭐️ destroy our git history as this is a hot-fix, that has been merged into the master branch but not the develop. We would have to have a look at the commit hash here, if it is the same as the one in the master we should be able to fix this somehow, if not, well ... I got a bad feeling about this.

**Comment by robertpainsi** [comment]
Ah, yes. For hot-fixes no rebasing of course. :smile_cat:
It's :dizzy:quite obvious:dizzy: that these merge commits are from the master branch and therefore this is a hot-fix. My fault. :flushed:

**Comment by thmq** [comment]
Alright then! Still good to have someone ask questions like these 😉

**Pull request merged**
