### PR TITLE
CAT-1097 Inconsitent text highlighting in Formula Editor

### PR DESCRIPTION
**Pull request by obusher**
Reopening of #1152.

### CODE REVIEW

**Comment by avihric** [comment]
UX team needs to decide on color

**Comment by obusher** [comment]
@avihric I would prefer pink! Did the UX team already decide about the color? :crocodile:

**Comment by obusher** [comment]
@avihric  COLOR!?! :dancer:

**Comment by avihric** [comment]
@obusher sorry I still need to contact UX team

**Comment by avihric** [comment]
Sry @obusher I didn't see the info in all the daily mail flood. It should be the dafault color, like stated in the ticket itself...

**Comment by Achilles-96** [comment]
Exactly, I put the same color as mentioned in ticket

**Comment by avihric** [comment]
@obusher Mind reopening the PR?

**Comment by obusher** [comment]
#1348 :)

**Comment by robertpainsi** [comment]
*deadlock*

**Pull request closed without merging**
