### PR TITLE
CATROID-1519 fixed unresolved imports in org.catrobat.catroid(test) file

### PR DESCRIPTION
**Pull request by Aayush2111**
Jira ticket: https://jira.catrob.at/browse/CATROID-1519

Fixed unresolved imports in org.catrobat.catroid(test) file

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Aayush2111** [comment]
@sebastiangollob @mseiser 
Please review the changes and provide any feedback that you may have.
Thank you! :)

**Review by sebastiangollob — CHANGES_REQUESTED** [review]
https://github.com/Catrobat/Catroid/pull/4703#pullrequestreview-1314434743

**Comment by sebastiangollob** [comment]
The issue is partly related to #4672

**Review by sebastiangollob — APPROVED** [review]

**Comment by mseiser** [comment]
How to reproduce this issue?

**Comment by sebastiangollob** [comment]
See also #4710 as it is a duplicate

**Comment by mseiser** [comment]
> See also #4710 as it is a duplicate

thanks 👍

**Comment by mseiser** [comment]
merged with #4710

**Comment by mseiser** [comment]
reopened because issue still persited

**Review by mseiser — APPROVED** [review]

**Pull request merged**
