### PR TITLE
HOTFIX - fix facedetection with stand alone apk

### PR DESCRIPTION
**Pull request by martinbu**
This is the HOTFIX that fixes the problem with facedetection in the stand alone apks.
Additionally facedetection and phiro bricks/sensors gets enabled if some of them are used in a program automatically.
Also Lego and Phiro Bricks works now correctly with other resources.

Due to the changes 2 face detection tests are failing. They will be fixed soon.
Please test this fix with stand alone apks, phiro and lego robot before merging!

### CODE REVIEW

**Comment by obusher** [comment]
It would be nice to have only one testclass for all setttings and not for every setting a testclass.

@martinbu @avihric : It looks like we do not test any `LegoNXT` settings. (Not important for this hotfix...)

**Comment by martinbu** [comment]
@obusher: LegoNXT settings are testet in (ui)test/devices/mindstorms/nxt

This PR should be merged after testing to the develop or master. Also @X4mp have to integrate these changes to the standalone apk branch. In my opinion we should host the standalone apk branch in the official catrobat repo not on an extern repo.

**Comment by avihric** [comment]
ping @martinbu any updates?

**Comment by robertpainsi** [comment]
> ...In my opinion we should host the standalone apk branch in the official catrobat repo not on an extern repo.

:+1: ping @X4mp

**Comment by X4mp** [comment]
Yes of course.
I wasn't able to push it myself, and due to time issues I just hosted it on my github account. For the future we can merge the branch to the official repository.
The next step would be to integrate the fix from @martinbu into my branch.

**Comment by thmq** [comment]
so this PR should actually be made onto @X4mp 's repository. and then the stand-alone apk branch should be moved into the official repo.

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
A significant number of tc are failing. This needs to be reworked properly. @martinbu Do you have time? :sparkles:

**Comment by martinbu** [comment]
@avihric Yes I now that tests are failing. But I have to wait for @X4mp to integrate my changes in his standalone apk branch. In my opinion this pull request can be closed and will be created again when we have finished.

**Comment by avihric** [comment]
Closing on behalf of @martinbu

**Pull request closed without merging**
