### PR TITLE
CATROID-804 Replace privacy dialog with link to privacy policy web page

### PR DESCRIPTION
**Pull request by devsebastian**
Ticket: https://jira.catrob.at/browse/CATROID-804
### Replace privacy dialog with link to privacy policy web page
Changes:
 - Removed the PrivacyPolicyDialogFragment
 - Added intent to open Privacy Policy in the browser
 - Changed the PrivacyPolicyDisclaimerTest to now check the "Privacy Policy" menu item and intent call.
 - Added a second test to test whether the (privacy policy) page actually exists in the web.
 - Removed unwanted resources namely:
    1. R.layout.dialog_privacy_policy.xml
    2. R.string.back
    3. R.string.dialog_privacy_policy_title
    4. R.string.dialog_privacy_policy_declined_text

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by wslany — CHANGES_REQUESTED** [review]
Awesome! 

Please only include the default values/string.xml file. All other localized versions are not to be directly edited in the repo, because they will be automatically overwritten by the import from https://translate.catrobat.org/ before a release.

Please squash to one commit. 

The dialog for Terms of Use and Service in the overflow menu cannot open the web page anymore. This needs to be corrected.
image
The reported error is:
`11-08 12:22:16.563 W/URLSpan ( 2151): Actvity was not found for intent, Intent { act=android.intent.action.VIEW dat=/pocketcode/termsOfUse (has extras) }
`
Please also add a test case.

The same problem, surprisingly, does not occur for the links in the About dialog that is also reachable via the overflow menu. Duplicate code?

Also, the Catrobat community sharing site is not accessible. Tapping on the button just leads to an empty screen instead of opening the webview. There must be missing tests so that this did not lead to a failed test. 

Also, accessing the media galleries to download looks and sounds does not work. Again, there seem to be missing test cases (independent of the PR?).

**Comment by devsebastian** [comment]
Sorry, the bug seems to have been caused due to editing of the wrong strings.xml file giving unwanted results, otherwise, I had not changed anything that would cause behavior changes in any view other than the privacy policy dialog, I reverted my commit and only changed the values/strings.xml file. The app is working perfectly now in the expected manner.

**Comment by wslany** [comment]
Thanks. Please squash to one commit.

**Comment by wslany** [comment]
Also, please fix the lint issue https://jenkins.catrob.at/job/Catroid/job/PR-3861/5/analysis/

**Review by wslany — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
