### PR TITLE
CAT-2333 Username stripped of whitespaces and test was added for the same

### PR DESCRIPTION
**Pull request by demonicode**
this is regarding this issue
https://jira.catrob.at/browse/CAT-2333

this is my first pull request, i know there would be mistakes. please tell me about them.

### CODE REVIEW

**Comment by bernadettespieler** [comment]
please add the CAT-number to the message

**Comment by demonicode** [comment]
Done

**Comment by robertpainsi** [comment]
@demonicode, you just changed the Pull Request header. This is also great and should be done, but it doesn't link the jira ticket to the corresponding PR yet. You have to add the Jira identifier to the __git__ commit message header.

**Comment by demonicode** [comment]
understood , so i have to commit again right, with proper commit message.

**Comment by robertpainsi** [comment]
I know I shouldn't comment on git or source stuff without reviewing your changes at least a little bit to know if the changes intending the correct thing, but since we are already on it. Please do not change following files:

* build.gradle
* catroid/build.gradle
* gradle-wrapper.properties

Please also squash your commits into a single commit at the end. :smile:

**Comment by 84n4n4** [comment]
please exclude the .iml files and misc.xml file from the commit.

**Comment by demonicode** [comment]
moved the issue to here - https://github.com/Catrobat/Catroid/pull/2239
this one became to messy for no reason. Please close this request.

**Pull request closed without merging**
