### PR TITLE
Allow dependency injection in fragments

### PR DESCRIPTION
**Pull request by SimonStefan**
depends on #3353 and #3365 
Implementing dependency injection for MainMenuFragment, SceneListFragment and SpriteListFragment

### CODE REVIEW

**Comment by SimonStefan** [comment]
@catrobatjenkins test this please

**Comment by SimonStefan** [comment]
@catrobatjenkins test this please

**Comment by SimonStefan** [comment]
@ThomasSchwengler please review this pull request

**Comment by SimonStefan** [comment]
@catrobatjenkins test this please

**Comment by SimonStefan** [comment]
@catrobatjenkins test this please

**Comment by jampo** [comment]
test this please

**Comment by SimonStefan** [comment]
@jampo I cannot see which tests might have failed because the link to Jenkins does not work. I rebased this pull request and fixing failed tests several times I did not receive any response. Could you please take a look at the code if it meets the general expectations?

**Comment by DinosaurierRex** [comment]
Rebased and reopened at [PR-3650](https://github.com/Catrobat/Catroid/pull/3650)

**Pull request closed without merging**
