### PR TITLE
CATROID-967 Convert brick pngs to xml

### PR DESCRIPTION
**Pull request by Tamdav**
- Create an XML file for each brick and changed the bricks in the project.
- It is not possible to create just one brick file per size and change the color of one path dynamically. So we need one file per color per size.
- Also had to make small changes to some brick files.
- As it is not possible to define a textarea in xml vector files - like it was the case with 9-Patch images - the padding on the left was added manually within the BrickLayout (and changes dynamically with the screen width).

https://jira.catrob.at/browse/CATROID-967

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by mstoeg — APPROVED** [review]
Looks good - reviewed in PP.

**Review by wslany — COMMENTED** [review]
Thanks, looks very nice. One question though: why do some bricks need more space than others? See, e.g., 
image

**Comment by Tamdav** [comment]
Each brick is assigned a style. For example, when creating the brick "Vibrate for 1 second", the style 'small' was assigned. The other two in your example have been assigned the style 'medium' and this style is by default larger than the style 'small'. But I can change these bricks to the smaller style if you like.

**Comment by wslany** [comment]
> Each brick is assigned a style. For example, when creating the brick "Vibrate for 1 second", the style 'small' was assigned. The other two in your example have been assigned the style 'medium' and this style is by default larger than the style 'small'. But I can change these bricks to the smaller style if you like.

Please make them all small by default. I wonder why we did that --- probably it was not a conscious decision. 

Note: There may be some accessibility setting where the spacings and fonts are larger, but I am not sure whether that influences above size type or not. 

One more thing is that the overview of categories seems to need more space per category. Here how it was before:
image

With this PR, it now looks like this:
image

I would say that making that spread out is not useful --- actually, the less vertical space needed, the less scrolling is needed for the user. Can we make that more compact without loosing the nice design?

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
