### PR TITLE
CATROID-739 Change dialog options for deletion

### PR DESCRIPTION
**Pull request by Veve8010**
https://jira.catrob.at/browse/CATROID-739

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by juliajulie95 — CHANGES_REQUESTED** [review]
Please fix this test:
org.catrobat.catroid.uiespresso.content.brick.app.PlaySoundBrickTest.testDeleteSound

**Review by juliajulie95 — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Seems a lot of related tests are now failing, see https://jenkins.catrob.at/job/Catroid/job/PR-3943/3/testReport/ , for instance org.catrobat.catroid.uiespresso.formulaeditor.FormulaEditorDeleteVariableTest.deleteVariableTest(FormulaEditorDeleteVariableTest.java:78) and many more related to this PR.

**Comment by juliajulie95** [comment]
@wslany Ich checked the failing tests at develop and the same ones where failing there. Also the tests failing on jenkins run through locally for me

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
