### PR TITLE
CATROID-1217 Added CLT for "If ___ true then ... else ..." brick

### PR DESCRIPTION
**Pull request by sahil9001**
Added Catrobat Language test as `testIfTrueThenElse.catrobat` in reference to https://jira.catrob.at/browse/CATROID-390 which solves the ticket https://jira.catrob.at/browse/CATROID-1217

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by sahil9001** [comment]
@wslany As mentioned [here](https://github.com/Catrobat/Catroid/pull/4312#issuecomment-902489146), I've added a Catrobat Language test, please share your review. I'm currently doing the other mentioned tasks, was to create a user-project in Catroid and adding tests to the [PR](https://github.com/Catrobat/Catroid/pull/4317)

**Comment by sahil9001** [comment]
@petbuer Can you please check this too, it's been over a month and I'm sorry to ask you like this.

**Comment by petbuer** [comment]
Yes, sorry for the delay!
The reason nobody saw this is, that the Jira ticket is still in the issues pool.
I will have a look.

**Comment by petbuer** [comment]
Thanks!
I think we first have to fix the "IfThen" Language Test, because it fails frequently on Jenkins (see https://jira.catrob.at/browse/CATROID-1225). Once this other test is fixed you can implement the "IfThenElse" Test in the same way.

**Comment by sahil9001** [comment]
@petbuer When I'm running the test on my device, it's running fine and showing me the "Success" message, can you tell me how its failing?

**Comment by petbuer** [comment]
Yes, it works locally, but somehow it fails on Jenkins. Our product owner needs to specify the expected behaviour of Lists in the if condition, this seems to be the problem, and then https://jira.catrob.at/browse/CATROID-1225 will be fixed. I am afraid, you have to wait a bit in the meantime until this ticket can be merged.

**Comment by sahil9001** [comment]
> Yes, it works locally, but somehow it fails on Jenkins. Our product owner needs to specify the expected behaviour of Lists in the if condition, this seems to be the problem, and then https://jira.catrob.at/browse/CATROID-1225 will be fixed. I am afraid, you have to wait a bit in the meantime until this ticket can be merged.
> 

Sure, I'll wait!

**Comment by petbuer** [comment]
Hi @sahil9001, sorry for the long wait, https://github.com/Catrobat/Catroid/pull/4395 is merged now, this should be a good guide for your test. You can use the same test cases but please be aware that conditions can lead to the IF branch, the ELSE branch or NEITHER being executed. Please check which of the three is the case for each test case (e.g. by setting a control variable in the IF and ELSE branch and also minding the possibility neither IF nor ELSE is taken).

**Comment by Anshul-9923** [comment]
Hi @petbuer Can you please review and merge my PR?
PR Link: https://github.com/Catrobat/Catroid/pull/4432

**Comment by sahil9001** [comment]
> Hi @sahil9001, sorry for the long wait, #4395 is merged now, this should be a good guide for your test. You can use the same test cases but please be aware that conditions can lead to the IF branch, the ELSE branch or NEITHER being executed. Please check which of the three is the case for each test case (e.g. by setting a control variable in the IF and ELSE branch and also minding the possibility neither IF nor ELSE is taken).

Sure, @petbuer I'll work on this and respond you ASAP!

**Pull request closed without merging**
