### PR TITLE
CAT-1315 Disable undo button after switching when editing

### PR DESCRIPTION
**Pull request by StefanBuerscher**
CAT-1315 Disable undo button after switching when editing
text

### CODE REVIEW

**Comment by robertpainsi** [comment]
Please provide a test and reword your commit message.

**Comment by StefanBuerscher** [comment]
Please tell me a good commit message...

**Comment by robertpainsi** [comment]
> Please tell me a good commit message...

No, but take a look at your commit message again:
```
    CAT-1315 Disable undo button after switching when editing
    
    cat1315 disable undo button disabled after
    switching when editing text
    
    CAT-1315 Disable undo button after switching when editing
```

You should also take a look at: https://wiki.openstack.org/wiki/GitCommitMessages

**Comment by StefanBuerscher** [comment]
#1327

**Pull request closed without merging**
