### PR TITLE
CAT-2644 Remove Google CodeIn splashscreen

### PR DESCRIPTION
**Pull request by rschluesselbauer**
The splashscreen will not be needed in the future so it is fully removed.

### CODE REVIEW

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
here is what happened on Jenkins: https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidTriggerPullRequestTest/3214/

@84n4n4, @cheidenreich  do you know anything about these warnings?

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
@thmq 

insteresting :-)

the Jenkins run, that you linked, aswell as the current one linked in the checks run on the followin PR:
(Reference build: #3211 | origin/pr/2655/merge)
(Reference build: #3211 | origin/pr/2655/merge)

this PR however is:
https://github.com/Catrobat/Catroid/pull/2666

so jekins is either running the wrong PR, or commenting on the wrong one....

funky...

**Pull request merged**
