### PR TITLE
MUS-198 Implement feature toggles

### PR DESCRIPTION
**Pull request by rohmab06**
Add feature toggle to build file to disable entry point for pocket music

### CODE REVIEW

**Comment by paggerbua** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
Since automatically updating the build status via Jenkins does not work, here is the result: https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidTriggerPullRequestTest/335/

Please have a look at the [meeting notes](https://confluence.catrob.at/display/CAT/2016-06-29+Meeting+notes), where the steps to a successful PR are listed.

**Pull request merged**
