### PR TITLE
CAT-2593 refactor SceneStartBrickTest

### PR DESCRIPTION
**Pull request by batmanandrobin**
Refactored SceneStartBrickTest.

### CODE REVIEW

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
ive got quite a few questions, maybe you got time this week so we can chat abou this PR

**Comment by batmanandrobin** [comment]
I'll be in the team room tomorrow afternoon

**Comment by 84n4n4** [comment]
please wait until https://github.com/Catrobat/Catroid/pull/2682 is finally done and merged and then refactor to remove all activity switching and just verifying that the brick works

**Pull request closed without merging**
