### PR TITLE
CAT 1703 Remove Camera Picker

### PR DESCRIPTION
**Pull request by davidmarogy**
Currently we have the problem if the device dont have a camera, we would see in the settings the Select camera setting, but this isnt very nice so we check if the device has some camera, if not the setting for choosing a camera is disabled.

### CODE REVIEW

**Comment by thmq** [comment]
I think this will have to be reviewed after the changes made bei @KohlThomas.

**Comment by avihric** [comment]
You should also squash your commits, actually fixup because the second is the same as the first.
By the way, when you rewrite your commit change it to `CAT-1703` in order that Jira tracks it correctly. The `-` is important.

**Comment by wslany** [comment]
@davidmarogy please do not spend time on this branch as the camera selection has been removed and is now only possible via a dedicated "Select front/back camera" brick in the latest release candidate. This brick will always remain visible, independently of the availability of a camera.

**Comment by thmq** [comment]
already implemented in #1387 ([CAT-1566](https://jira.catrob.at/browse/CAT-1566)).

**Pull request closed without merging**
