### PR TITLE
CAT-1168 Uncommented Test

### PR DESCRIPTION
**Pull request by loibi93**
Removed Commenting from UserConceptTest class.

### CODE REVIEW

**Comment by loibi93** [comment]
Seems that Jenkins did a restart during the test !? But i think it is sufficient if i just do a singleclass test with the UserConceptTest class since nothing but that class has changed !

**Comment by obusher** [comment]
Console:
`12:01:54 org.catrobat.catroid.uitest.web.UserConceptTest:....INSTRUMENTATION_RESULT: shortMsg=java.lang.NullPointerException
12:01:54 INSTRUMENTATION_RESULT: longMsg=java.lang.NullPointerException
12:01:54 INSTRUMENTATION_CODE: 0`
Logcat:
`java.lang.NullPointerException at android.support.v4.app.DialogFragment.show(DialogFragment.java:125) at org.catrobat.catroid.ui.dialogs.LoginRegisterDialog.onRegistrationComplete(LoginRegisterDialog.java:113)`

**Comment by loibi93** [comment]
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-Device-Single-ClassAndPackage-Test/322/

**Comment by obusher** [comment]
The whole testrun gets aborted, so it does not matter much if the single-run is green.

**Comment by obusher** [comment]
ok to test

**Comment by loibi93** [comment]
Sorry, i thought that this log means only one test failed ;)

**Comment by loibi93** [comment]
Failed again for the same reason, but as i said, a Single Class test is sufficient here, because the only thing that changed was the test class, and not actual App Code.

**Comment by robertpainsi** [comment]
> Failed again for the same reason, but as i said, a Single Class test is sufficient here, because the only thing that changed was the test class, and not actual App Code.

Unfortunately not. Jenkins has to be kept stable but at least runnable (especially the PR run) otherwise it can't be used anymore :scream_cat: I'll give the PR a quick rerun but if it fails again, it's not mergeable and has to be fixed to run a full testrun as well.

Since the exception is thrown by an AsyncTask, the root of the problem can be really hard to find. And if you are unlucky, the problem occurs because another test doesn't clean up the resources correctly.

**Comment by robertpainsi** [comment]
ok to test

**Comment by loibi93** [comment]
Ok, thats a good reason ;D
I didn't have a look what exactly went wrong, but since it ran fine on the device, it is possible that the test breaks on emulator ! Is it possible to force jenkins using the device instead of emulator ? I would suggest that i test that out before doing the dig ;D

**Comment by robertpainsi** [comment]
> Is it possible to force jenkins using the device instead of emulator

You can use the ```@Device``` annotation
https://github.com/Catrobat/Catroid/blob/develop/catroidTest/src/org/catrobat/catroid/uitest/content/interaction/BrickEditFormulaTest.java#L51

However, I don't know the device annotation policy. Meaning, I don't know when it's acceptable to use it. We once tried to move as many tests as possible to the emulators because they run so much faster.
ping @avihric @obusher

**Comment by loibi93** [comment]
At least the tests won't crash anymore ! Not sure why the three tests failed.

**Comment by avihric** [comment]
@robertpainsi There is no real policy, so if you argue that this test is only runable on Device otherwise it won*t succeed, thats fine.

@loibi93 you have 2 checkstyle warnings, pls fix them.
**Tip**: Use gradle task checkstyle before commiting, it performs the same checks as on Jenkins

**Comment by obusher** [comment]
Maybe we should comment those tests, which only are runable on Device but technically should be run on emulator, with something fancy like `//Aborts on emulator` .

**Comment by loibi93** [comment]
@avihric I am not sure how to fix these warnings, where do i have to put the imports ?

**Comment by robertpainsi** [comment]
@obusher: :+1: 
@loibi93: Ctrl+Alt+O also known as Optimize imports :wink:

**Comment by loibi93** [comment]
Thanks very much :D

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-Device-Single-ClassAndPackage-Test/327/

https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-Device-Single-ClassAndPackage-Test/326/

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-Device-Single-ClassAndPackage-Test/328/

Ok to merge.

**Comment by thmq** [comment]
fix the commit message according to our policy, furthermore it is not just a few failing test cases, the emulator run crashes entirely and the device run is not even started. as @robertpainsi said: the PR has to be runnable on Jenkins at least.

**Comment by loibi93** [comment]
Commit message has already been fixed ;)

The recent run was because of the new commit message, here is the stale run:
https://jenkins.catrob.at/job/Catroid-PullRequest-TestJob/583/

and the failed test in a single run:
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-Device-Single-ClassAndPackage-Test/328/

**Comment by avihric** [comment]
Could you rewrite your commit msg with: 

```
CAT-1168 Uncommented Test

Reintroduced UserConceptTest class
```

**Comment by loibi93** [comment]
Rebased and changed Commit message !

**Pull request merged**
