### PR TITLE
CAT-874 "repeat until" and "wait until" bricks

### PR DESCRIPTION
**Pull request by p4p4**
New Bricks:
- Wait Until: waits until a specified condition evaluates to true

Repeat Until:
-  A loop that gets executed as long as the specified condition evaluates to false.
-  Aborted or skipped when the specified condition evaluates to true

This PR includes 3 TestCases: WaitUntilActionTest, RepeatUntilActionTest and RepeatUntilBrickTest

reviewed & refactored

Checkstyle OK:
- [jenkins CatroidCheck results](https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/226/)

Tests:
- [jenkins package 'test' results](https://jenkins.catrob.at/job/CatroidSinglePackageEmulatorTest/2121/)
- this pull does not break any tests
-- the two failing tests already fail in the current develop branch: [results for 'develop' branch](https://jenkins.catrob.at/job/CatroidSinglePackageEmulatorTest/2120/)

### CODE REVIEW

**Comment by p4p4** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
retest this please

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
retest this please

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
retest this please

**Comment by thmq** [comment]
retest

**Comment by thmq** [comment]
retest

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
retest this please

**Comment by thmq** [comment]
test this please

**Comment by p4p4** [comment]
@catrobatjenkins ist sauer!

**Comment by p4p4** [comment]
thanks for merging, @Bioxar :+1:

**Pull request merged**
