### PR TITLE
CATROID-615 New build-parameter to build Catroid PRs with Paintroid develop branch on Jenkins

### PR DESCRIPTION
**Pull request by ldirry**
added build parameter "BUILD_WITH_PAINTROID", so that the current PR can be build with the current Paintroid develop branch. The produced apk is available as artifact: catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug.apk. 

I tested it by temporarily replacing the Catrobat/Paintroid develop branch (in the changed jenkins file), with a branch on my ldirry/paintroid where I displayed a short toast (obviously had to change it back to develop Catrobat/Paintroid).

https://jira.catrob.at/browse/CATROID-615

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks. I see that the following files are kept, but I think that the two paintroid apks und the unnamed catroid apk are not necessary to be kept, no? Only the catroid-catroid-debug-PR-4201-32.apk with the Paintroid develop branch lib files should remain.

**Comment by wslany** [comment]
Note: It seems to me that the new AARs are not contained in the catroid-catroid-debug-PR-4201-32.apk file but instead in the catroid-catroid-debug.apk --- that's OK then, both can be kept if that's not possible otherwise.

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks, this works mostly fine now.But now the BUILD_ALL_FLAVOURS option does not work anymore: 
image

This should produce something like (from another PR):
image

However, the APKs of the flavors are not there:
image
Or, on the detail page:
image

**Comment by ldirry** [comment]
> Thanks, this works mostly fine now.But now the BUILD_ALL_FLAVOURS option does not work anymore:
> image
> 
> This should produce something like (from another PR):
> image
> 
> However, the APKs of the flavors are not there:
> image
> Or, on the detail page:
> image

ah sorry, totally forgot about them :x

but now if build with the new paintroid flag (and the flavor parameter is chosen), these apk get build with the develop paintroid branch and archived. 
and if not built with the paintroid flag, they will get built as usual

**Comment by wslany** [comment]
Will be taken over by @juliajulie95 in another PR.

**Pull request closed without merging**
