### PR TITLE
CATROID-415 - ProjectActivity crash onBack when current project is null

### PR DESCRIPTION
**Pull request by 84n4n4**

### CODE REVIEW

**Comment by 84n4n4** [comment]
we got rid of a lot of cascading crashes with the last release, this one here still seems to be the last of those.
if the current project == null, the project activity should be finished (which is what the users seem to try here anyways) since nothing can be performed there anyways in this state.

**Comment by 84n4n4** [comment]
btw. this is currently the highest ranking crash with over 100 occurences. (second highest with ~40 in CATROID-439)

**Comment by wslany** [comment]
Just saying...: https://kotlinlang.org/docs/reference/null-safety.html

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
