### PR TITLE
CATROID-1450 Add a demoproject for the Embroidery Designer

### PR DESCRIPTION
**Pull request by mseiser**
Implements new example project with frame for embroidery designer. 
The old default project didn't include the frame object, which helps user define the area of where to code their embroidery pattern.

Remarks:
Instead of white needle, the black one is used because it is already used in the current default project. For now the example project is just swapped with the framed example project. Maybe in the future users should be able to choose between different example projects (depending on the version).

https://jira.catrob.at/browse/CATROID-1450

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by Tamdav — APPROVED** [review]
looks good!

**Review by wslany — CHANGES_REQUESTED** [review]
There are no tests. *Always* add tests, and develop in TDD way (write tests *first*, and check that they fail).

Tests for the default project of Catroid exist:
* https://github.com/Catrobat/Catroid/blob/develop/catroid/src/androidTest/java/org/catrobat/catroid/test/common/DefaultProjectHandlerTest.java
* https://github.com/Catrobat/Catroid/blob/develop/catroid/src/androidTest/java/org/catrobat/catroid/test/utiltests/DefaultProjectComparatorTest.java

Please add similar (or better) tests for the Embroidery Designer default project.

**Review by wslany — COMMENTED** [review]
Also, please change the project itself so that it is programmed in a more understandable and shorter  way. Each petal currently is drawn independently in one very large script (40 bricks) with 5 triple nested loops etc --- this is not easy to understand for human users, especially for beginners, and contains lots of repeated code (= code duplication). It would be much better to add a well-named user defined brick for a petal, which has a parameter to draw the petal in a certain direction from the current position. The number of bricks should be reduced to around 10, with a clear name of the user defined brick for the petal.

**Comment by mseiser** [comment]
closed because of merging issue with commits

**Pull request closed without merging**
