### PR TITLE
CAT-2458 Make collision events work with clones

### PR DESCRIPTION
**Pull request by rschluesselbauer**
- Make collision broadcast messages individual for each clone
- Give each clone its own BroadcastSequenceMap
- Call broadcast listeners for clones too

Edit:
- Add small test for collision broadcast messages of a clone

### CODE REVIEW

**Comment by 84n4n4** [comment]
this breaks the airfight game, after a handful of cloned bullets have been shot the controls get broken   / unresponsive

**Comment by 84n4n4** [comment]
the broadcast system is fubar, the clone system also. we should discuss how to go from here, since fixing one bug opens 20 new ones now.

**Comment by robertpainsi** [comment]
I'm not sure if you just refer to the physics collision event handling or the whole broadcast system.
I'm not familiar with the new broadcast implementation. However, the physics collision event handling has always been a mess and a hack. The clone feature has never been tested, and is also hacky in many places.

Maybe it's worth a GSoC project? To improve the whole event managing? Including restructuring, make it reusable, testable and much much more. So, we also start to improve the core and stage logic. What do you think?

I haven't researched yet how the event logic in scratch works, but since it's open sourced, maybe we can copy it somehow. https://github.com/LLK/scratch-vm

**Comment by 84n4n4** [comment]
@robertpainsi 
>>However, the physics collision event handling has always been a mess and a hack.

same same with the regular broadcast system

**Comment by rschluesselbauer** [comment]
@robertpainsi @84n4n4 I have done some refactoring of the bc system over the holidays - I'll show you the concept next time I see you.

> I haven't researched yet how the event logic in scratch works, but since it's open sourced, maybe we 
> can copy it somehow

Good call, I'll have a look at the way scratch does it.

**Comment by cheidenreich** [comment]
ok, I'll close this for now

**Pull request closed without merging**
