### PR TITLE
CATROID-626 Add a set of face detection sensors for a second face

### PR DESCRIPTION
**Pull request by blindguardian50**
FaceDetector can now easier be extended with additional sensors if necessary

https://jira.catrob.at/browse/CATROID-626

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by ndrnour — DISMISSED** [review]
could you please rebase develop branch into this PR's branch and push again

**Review by adnaribo — CHANGES_REQUESTED** [review]
really good work :+1: I tested it on the device and the x position of the second face in landscape mode is not working correctly, and the second face detection does not work with the rear camera, could you please look into this :)

**Review by adnaribo — APPROVED** [review]
Looks good :+1:

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
