### PR TITLE
CATROID-1014 Splash screen at end of execution of standalone APKs should have link to the Huawei AppGallery

### PR DESCRIPTION
**Pull request by CodeChamp-SS**
The splash screen at end of execution of standalone APKs now has a link to the Huawei AppGallery, and a new design of the button that links to the Google Play Store.
The designs of both buttons are now the same as those on the share site.

https://jira.catrob.at/browse/CATROID-1014

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks! Please fix the warnings on https://jenkins.catrob.at/job/Catroid/job/PR-4081/3/analysis/

Also, please make sure the buttons are the same size on the screen:
image

And I found that there is an error when leaving the app by tapping the Android back button on the final splash screen, but it occurred already before this pull request and also seems to have been solved in #4077 so there's nothing further for you to do here. Just fro completeness, here's the stacktrace:
```
04-07 05:19:10.428 E/WindowManager(27894): android.view.WindowLeaked: Activity org.catrobat.catroid.ui.MainMenuActivity has leaked window DecorView@259f71d[MainMenuActivity] that was originally added here
04-07 05:19:10.428 E/WindowManager(27894): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:765)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:440)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Dialog.show(Dialog.java:473)
04-07 05:19:10.428 E/WindowManager(27894): 	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
04-07 05:19:10.428 E/WindowManager(27894): 	at org.catrobat.catroid.ui.MainMenuActivity.showTermsOfUseDialog(MainMenuActivity.java:137)
04-07 05:19:10.428 E/WindowManager(27894): 	at org.catrobat.catroid.ui.MainMenuActivity.onCreate(MainMenuActivity.java:98)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Activity.performCreate(Activity.java:7957)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Activity.performCreate(Activity.java:7946)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.os.Looper.loop(Looper.java:237)
04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
04-07 05:19:10.428 E/WindowManager(27894): 	at java.lang.reflect.Method.invoke(Native Method)
04-07 05:19:10.428 E/WindowManager(27894): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-07 05:19:10.428 E/WindowManager(27894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by CodeChamp-SS** [comment]
> Thanks! Please fix the warnings on https://jenkins.catrob.at/job/Catroid/job/PR-4081/3/analysis/
> 
> Also, please make sure the buttons are the same size on the screen:
> image
> 
> And I found that there is an error when leaving the app by tapping the Android back button on the final splash screen, but it occurred already before this pull request and also seems to have been solved in #4077 so there's nothing further for you to do here. Just fro completeness, here's the stacktrace:
> 
> ```
> 04-07 05:19:10.428 E/WindowManager(27894): android.view.WindowLeaked: Activity org.catrobat.catroid.ui.MainMenuActivity has leaked window DecorView@259f71d[MainMenuActivity] that was originally added here
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:765)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:440)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Dialog.show(Dialog.java:473)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at org.catrobat.catroid.ui.MainMenuActivity.showTermsOfUseDialog(MainMenuActivity.java:137)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at org.catrobat.catroid.ui.MainMenuActivity.onCreate(MainMenuActivity.java:98)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Activity.performCreate(Activity.java:7957)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Activity.performCreate(Activity.java:7946)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.os.Looper.loop(Looper.java:237)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at java.lang.reflect.Method.invoke(Native Method)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 04-07 05:19:10.428 E/WindowManager(27894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
> ```

I am not sure about how to fix the Jenkins warnings, and I think those existed even before this pr 😅, and I'll make the buttons of the same size.

**Comment by CodeChamp-SS** [comment]
@wslany made the buttons of the same size.

**Comment by CodeChamp-SS** [comment]
@wslany sir, any updates on this pr?

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
