### PR TITLE
CAT-1440 Cancelling creating a new variable

### PR DESCRIPTION
**Pull request by StefanBuerscher**
will no longer name the variable "New..."

### CODE REVIEW

**Comment by avihric** [comment]
retest this please

**Comment by avihric** [comment]
:one: checkstyle warning...

**Comment by StefanBuerscher** [comment]
Where can I see the checkstyle warning? When running Gradle:check and Gradle:checkstyle locally there is no warning

**Comment by robertpainsi** [comment]
Click on "Details" on the right side of "All checks have failed" and then on the corresponding build numbers. [Shortcut](https://jenkins.catrob.at/job/Catroid-Build-SourceTests-StaticChecks/3085/checkstyleResult/new/)

Jenkins tests the merge of both branches, develop and yours. This is mandatory to keep a healthy develop branch and app. Just rebase your branch and run the gradle check again ;)

**Comment by StefanBuerscher** [comment]
I found a bug in my implementation that I could not fix yet. I think CAT1440 will not be fixed for the current release.

**Comment by avihric** [comment]
Please reopen PR when u have solved the issue

**Pull request closed without merging**
