### PR TITLE
Update OkHttp to 2.3.0, kill ConnectionWrapper

### PR DESCRIPTION
**Pull request by aried3r**
Same as #1207 but with target `release`.

### CODE REVIEW

**Comment by aried3r** [comment]
ok to test

**Comment by aried3r** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by aried3r** [comment]
ping @avihric

**Pull request merged**
