### PR TITLE
 Add ActionBar to SettingsActivity

### PR DESCRIPTION
**Pull request by ndrnour**

### CODE REVIEW

**Comment by 84n4n4** [comment]
test this please

**Comment by ndrnour** [comment]
Closed! why ?

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
**I've deleted this line** 
`app:titleTextAppearance="@style/ToolbarTitle"` 
**from Layout toolbar, because it produces an error which is :**
`E/BaseExceptionHandler: uncaughtException: 
                        java.lang.RuntimeException: Unable to start activity ComponentInfo{org.catrobat.catroid/org.catrobat.catroid.ui.SettingsActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f04010f a=4}
                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                            at android.os.Handler.dispatchMessage(Handler.java:105)
                            at android.os.Looper.loop(Looper.java:156)
                            at android.app.ActivityThread.main(ActivityThread.java:6595)
                            at java.lang.reflect.Method.invoke(Native Method)
                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                         Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f04010f a=4}
                            at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:764)
                            at android.widget.TextView.setTextAppearance(TextView.java:2901)
                            at android.support.v7.widget.AppCompatTextView.setTextAppearance(AppCompatTextView.java:159)
                            at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:757)
                            at android.support.v7.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:261)
                            at android.support.v7.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:243)
                            at android.support.v7.app.ToolbarActionBar.<init>(ToolbarActionBar.java:74)
                            at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:217)
                            at org.catrobat.catroid.ui.AppCompatPreferenceActivity.setSupportActionBar(AppCompatPreferenceActivity.java:61)
                            at org.catrobat.catroid.ui.SettingsActivity.updateActionBar(SettingsActivity.java:431)
                            at org.catrobat.catroid.ui.SettingsActivity.onCreate(SettingsActivity.java:136)
                            at android.app.Activity.performCreate(Activity.java:6910)
                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570) 
                            at android.os.Handler.dispatchMessage(Handler.java:105) 
                            at android.os.Looper.loop(Looper.java:156) 
                            at android.app.ActivityThread.main(ActivityThread.java:6595) 
                            at java.lang.reflect.Method.invoke(Native Method) 
                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) `

**Comment by ndrnour** [comment]
test this please

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by thmq** [comment]
well, there are some theming problems, but the titleTextAppearance is important for the accessibility settings, so you must not delete them.

the preferences should be refactored according to this:
https://developer.android.com/guide/topics/ui/settings.html#Fragment

for now we should probably leave it the way it is if it does not work with the preference activity (which I expected). if you care to fix this properly you should create a new AppCompatActivty and add the preferences as fragments (as described in the guide above). i will close this for now.

**Comment by ndrnour** [comment]
well, the problem is solved 
was because of there are no styles applied on the SettingsActivity besides to that ActionBar!
so i applied the same styles on it.
about refactoring according to that way : I disagree :(
it works for simple PreferenceActivity but not in our situation since we have 5 nested PreferenceScreens

**Comment by ndrnour** [comment]
please reopen the PR, I have no rights to do that!

**Comment by robertpainsi** [comment]
[How to reopen a pull-request after a force-push?](https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c)

**Comment by robertpainsi** [comment]
@ndrnour, I should've the rights, but I can't reopen it. Your branch currently points at https://github.com/ndrnour/Catroid/commit/47b2bf2d40ee5c4f9dcc66a9fb71de7ef55a41aa whereas the pull request pointed at https://github.com/Catrobat/Catroid/pull/2722/commits/6073079976be4168775f44be5a4bdfa191c4d2fe when it was closed.

Reset your remote branch to https://github.com/Catrobat/Catroid/pull/2722/commits/6073079976be4168775f44be5a4bdfa191c4d2fe first. If you still can't open it afterwards, just let me know.

**Comment by ndrnour** [comment]
i did reset, but still there is no "reopen Pr" button!

**Comment by ndrnour** [comment]
@robertpainsi  cool, just a question!
now after i do my changes. can i commit --amend ? or i have to push then merge the commits ?

**Comment by robertpainsi** [comment]
Ahm, I'm not sure what you exactly wanna achieve.
But you can do what ever you like :wink:. amends, merges, force pushes, etc.

You can also reset your local branch `ActionBarSettingActivity` to 47b2bf2d40ee5c4f9dcc66a9fb71de7ef55a41aa and then force-push the branch.

**Comment by ndrnour** [comment]
@robertpainsi  thanks, you are the best!

**Comment by ndrnour** [comment]
please run espresso tests

**Pull request closed without merging**
