### PR TITLE
Cat-1243

### PR DESCRIPTION
**Pull request by kaufi**
substitutes #1155 

we definately need a ticket for the Handlerleak Lint warning!

### CODE REVIEW

**Comment by kaufi** [comment]
it seems, that with the new version, all tasks for the tests have been renamed...
assembleDebugTest->assembleDebugAndroidTest and so on!
so we have to be careful, since this requires a change on the Jenkins side

**Comment by kaufi** [comment]
@avihric @SimonStefan shall we forget about the gradle plugin update (at least to the latest version) for now and use the latest possible version which is compatible with our current jenkins configuration?

**Comment by SimonStefan** [comment]
yes, I think we can postpone the update to version 1.1.x

**Comment by SimonStefan** [comment]
ok to test

**Comment by kaufi** [comment]
something is still not working - have to have a look into it; also strange, that on my local machine "gradle check" reports 0 lint warnings/errors, and here we have 2 of them :)

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by linsm** [comment]
ok to test

**Pull request merged**
