### PR TITLE
CAT-1300 VibrationBrickTest

### PR DESCRIPTION
**Pull request by BerndBaumann**
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Build-SourceTests-StaticChecks/2248/

https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/CatroidDeviceTest/1994/#showFailuresLink

https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-ParalellEmulatorUITest-CustomBranch/1732/

### CODE REVIEW

**Comment by robertpainsi** [comment]
Someone will tell you to squash your commits, I guarantee it! :wink: Also use the new commit message guidelines.

**Comment by avihric** [comment]
@BerndBaumann could you rewrite your commit msg with a preceding CAT-1300 please.
Sorry for the unclarity, I will update the contribution page asap.

**Comment by avihric** [comment]
:eyes: https://github.com/Catrobat/Catroid/wiki/Setup-working-environment#commit-guidelines

**Comment by avihric** [comment]
ping @BerndBaumann Do you have some time to update the PR?

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
retest this please

**Pull request closed without merging**
