### PR TITLE
CAT-1428 Temp workaround to hide physics collision broadcast messages

### PR DESCRIPTION
**Pull request by anddman**

### CODE REVIEW

**Comment by anddman** [comment]
re-run of failed tests: 
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/483/

**Comment by robertpainsi** [comment]
The temporary workaround will be removed/fixed before the physics engine is merged into the develop branch, right?

**Comment by anddman** [comment]
Nevermind, this would be more of a last resort quick&dirty workaround, a much nicer solution is being worked on.

**Comment by robertpainsi** [comment]
Great! :+1: Hopefully it's not too much work to do.

**Pull request closed without merging**
