### PR TITLE
Remove duplicate test util classes

### PR DESCRIPTION
**Pull request by robertpainsi**
Remove uitest Reflection class because there is an identical copy in
the package org.catrobat.catroid.test.utils. Also remove the Reflection
test which assures that both copies of the Reflection class are the
same.

### CODE REVIEW

**Comment by obusher** [comment]
Nice! :) Looks like there are some other duplicate classes in these directories too. (`XMLValidationUtil, SimulatedSensorManager, SimulatedSoundRecorder ...`)


Maybe we should create a `global-util` directory (package) to resolve the dependency of `uitest` from `test`.

**Comment by robertpainsi** [comment]
Ah, thanks for the tip @obusher !
I will take a look over all the duplicate utils classes. So please don't merge atm.

**Comment by robertpainsi** [comment]
@obusher: There is already a common package for the Bluetooth stuff. This would be a good place for all the common util classes too.

However, I don't like it :pouting_cat: because the classes
```org.catrobat.catroid.common.CatroidService``` and
```org.catrobat.catroid.common.SoundInfo``` aren't in the same project nor in the same folder even if it looks so.

Other developer should jump in and discuss it with you. \**slowly sneaking away*\*

**Comment by obusher** [comment]
Looks fine for now! :)

**Comment by robertpainsi** [comment]
The test.utils package it is... *for now*! :smile_cat:
Thanks!

I'll create a ticket to create a global/common/whatever package for the tests und uitests later in the evening.

**Comment by aried3r** [comment]
Most of this would be a lot easier with the intended directory structure of
Gradle, so I'd rather work on that.

**Comment by robertpainsi** [comment]
@aried3r: This is the current project structure in AS

screenshot from 2015-03-27 16 45 52

I don't see any difference to a newly created AS project (beside the internal representation on the file system itself). Smiley with question mark not found, using :confused:

**Pull request merged**
