### PR TITLE
CAT-1956 Remove implicit change of PhysicsObjectType via Bricks

### PR DESCRIPTION
**Pull request by anddman**

### CODE REVIEW

**Comment by robertpainsi** [comment]
I guess the whole `PhysicsObjectTypeDefaultValueTest` can be removed now.

**Comment by robertpainsi** [comment]
Do _not_ apply the unformatted code patch from the catrobatbot. It's a known limitation :beetle:. I currently can't find the comment where I mentioned it in the first place but if you only remove code from a package (in this case `org.catrobat.catroid (androidTest)`), the whole package is formatted. So unformatted but unrelated code will also be reported. Maybe I'll fix it some day...

**Comment by robertpainsi** [comment]
Close? No, merge :smirk_cat: (maybe?)

**Comment by anddman** [comment]
What's seems to be the problem with this PR?

**Comment by thmq** [comment]
retest this please

**Comment by thmq** [comment]
ok to test

**Pull request merged**
