### PR TITLE
CATROID-1208 Refactor use of "vh" string

### PR DESCRIPTION
**Pull request by ChriMoser**
Refactored the "vh" string to view_holder/ViewHolder in filenames and code.

[CATROID-1208](https://jira.catrob.at/browse/CATROID-1208)
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by Tamdav — APPROVED** [review]
looks good!

**Comment by ChriMoser** [comment]
Note: It seems that git is comparing some wrong files with each other!

- view_holder_list_with_headline.xml gets compared to view_holder_category_list_item_with_headline.xml
- view_holder_category_list_item_with_headline.xml gets compared to view_holder_variable_with_headline.xml
- view_holder_variable_with_headline.xml gets compared to view_holder_list_with_headline.xml

The content of the files is still correct and working!

(The error may also be with the refactor function of AndroidStudio)

**Comment by juliajulie95** [comment]
@ChriMoser please rebase again

**Review by wslany — DISMISSED** [review]
@ChriMoser please rebase and resolve conflicts.

**Comment by Walcho1125** [comment]
> @ChriMoser please rebase and resolve conflicts.

I rebased and resolved the conflicts, as @ChrisMoser is no longer active. Please review!

**Pull request merged**
