### PR TITLE
CATROID-436 No">" sign in brick category menu.

### PR DESCRIPTION
**Pull request by Gwzwnglai-AuBurn**
The ">" signs pertain to iOS and do not conform to Android style guidelines. They should not be shown.

Before:
largerthan

After:
Catroid-436

### CODE REVIEW

**Comment by PlantinumX** [comment]
pls squash commits to one commit and move ticket in jira

**Comment by Gwzwnglai-AuBurn** [comment]
Ok, I'm on it!

**Comment by Gwzwnglai-AuBurn** [comment]
Jenkins is showing a warning, is that a problem?

**Comment by Gwzwnglai-AuBurn** [comment]
@PlantinumX I think this is good now. 
So Jenkin's warning is about the Icons (png-files) not having xxhdpi pixel density versions 
and some of them not having mdpi and hdpi pixel densities. 
I notice that this warning shows up when then drawable icon resources are changed. 
Am I missing something?

**Comment by PlantinumX** [comment]
unfortunately pls fix jenkins warnings  otherwise we cannot merge your ticket although good work done until now (Y)

**Comment by Gwzwnglai-AuBurn** [comment]
Okay, I'll try to find some way to suppress the lint warnings.

**Comment by PlantinumX** [comment]
Hi @Gwzwnglai-AuBurn I looked at your PR pls do not use surpress warnings in the lint file. Now I willl explain step by step what you need to do. 
1) delete catroid/src/main/res/drawable-ldrtl-xhdpi/main_menu_button_arrow.png and catroid/src/main/res/drawable-xhdpi/main_menu_button_arrow.png
2)  delete the lint-baseline file and let gradle generate a new one. (go to Catroid directory and type in cmd  ./gradlew pmd checkstyle lintCatroidDebug detekt      )
3)  copy the catroid header into newly generated baseline file ()
4) add the changes and push

**Comment by Gwzwnglai-AuBurn** [comment]
I am not being able to fix this Build error
when running :
gradlew pmd checkstyle lintCatroidDebug detekt
`
[error.txt](https://github.com/Catrobat/Catroid/files/4352049/error.txt)
`
can you help me?

**Comment by Gwzwnglai-AuBurn** [comment]
I am not being able to fix this [build error](https://github.com/Catrobat/Catroid/files/4352074/error.txt)
`
\> Configure project :catroid
VersionCode is 73
VersionName is 0.9.69

\> Task :catroid:checkstyle FAILED

FAILURE: Build failed with an exception.

\* What went wrong:
Execution failed for task ':catroid:checkstyle'.
\> Unable to create Root Module: config {A:\Catroid\catroid\config\checkstyle.xml}, classpath {null}.

\* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

\* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date
`
when running :
gradlew pmd checkstyle lintCatroidDebug detekt
can you help me?

**Comment by PlantinumX** [comment]
If you give me write access to your forked repository I could the changes quickly

**Comment by Gwzwnglai-AuBurn** [comment]
Sure

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
