### PR TITLE
CATROID-70 remove unused broadcast message deletion on stage start

### PR DESCRIPTION
**Pull request by 84n4n4**

### CODE REVIEW

**Comment by wslany** [comment]
Where is it tested that unused messages are removed on project save / load, as described in CATROID-70?

**Comment by 84n4n4** [comment]
There is no list of messages serialized into the xml, only the bricks and their set message are serialized. On project load the list is populated by the messages set in bricks. A broadcast brick can have only one message.
So by design, broadcast messages that arent selected in any brick are not stored.

**Comment by 84n4n4** [comment]
unit test added that asserts that unused messages are not saved/loaded.

**Comment by wslany** [comment]
This means that the removal of unused messages works implicitly with the current design, but this feature will not be documented anymore in any way. Please remember: Our tests also serve as maintenance documentation. I wouldn't be very surprised if unused messages will not be removed anymore after some refactoring in two or three years, the reasoning being "nobody told me so, and it was not documented". Also, if this stays as it is, from now on every PO will have to check this manually for each PO review. Unacceptable ;-) The reversal of this functionality might actually be quite likely if we decide to not use XStream anymore and switch to a json format for the serialization, and somebody gets the idea that it would be good to list all messages somewhere in the code, e.g., in order to list them all at one place per scene, and use ids of messages in the code itself instead of the strings, which makes a lot of sense, e.g., if a feature gets implemented that allows to rename messages. I can alsmot guarantee that then suddenly unused messages will not be removed anymore. And also: the same argument of no-need-for-tests could be said for all functionality that works fine.

**Comment by 84n4n4** [comment]
@thmq @LPeteR90 @robertpainsi  can somone of you please review and reapprove this PR.

thank you!

**Comment by robertpainsi** [comment]
Can't someone else do it?

**Pull request merged**
