### PR TITLE
Failing Junit Device Tests

### PR DESCRIPTION
**Pull request by obusher**
Reopening of  #1235 with `base:release`.

### CODE REVIEW

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by avihric** [comment]
Seems that the build was not triggered. Im curious why `testAddNewLook` and `testWhenScriptRestartingItself` are failing and if it is consistent with your PR.

**Comment by avihric** [comment]
ok to test

**Comment by obusher** [comment]
I assume `testAddNewLook` is flaky, but i have started 2 manual PR tests for verification.
I can not check them now, because jenkins seems offline.
`BroadcastActionTest.testWhenScriptRestartingItself` is not fixed with this PR. (see CAT-1347) :tanabata_tree:

**Comment by avihric** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by avihric** [comment]
`testAddNewLook` is green in single run:
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/342/

**Pull request merged**
