### PR TITLE
CATROID-384 Enable edit of broadcast messages

### PR DESCRIPTION
**Pull request by mstoeg**
https://jira.catrob.at/browse/CATROID-384

- Refactor old testcases and add new ones for editing broadcast messages (including the test case for a message with the same text in a second scene, which should not be changed by the renaming in the first scene) - as it was asked for in the ticket specification

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by dandrawes — APPROVED** [review]
Well done!

**Review by wslany — CHANGES_REQUESTED** [review]
As implied by _Tapping "edit..." shall open the selected message (in the same text edit field as when defining a new message) and allow to edit it._ in https://jira.catrob.at/browse/CATROID-384 the existing name should be prefilled in the edit field. However, it currently is empty in the PR. Please change this so the old message is initially inserted when edited it. Reason: often, one only wants to correct a typo, or see the full text of the message, which may be longer than the one line field shown in the script view.

Also, when putting a script containing broadcast scripts into the backpack and unpacking them in another scene, leads to all messages being replaced visually by "edit...", see screenshot below. However, when selecting "edit..." and changing the message to, e.g., abc, and then pressing OK, the message remains "edit..." unchanged, and the new message abc is nowhere to be found in the spinner of messages. This also happened with only one scene, so it is not necessary to have two scenes, but this issue appears possible in a more repeatable way by creating a second scene first, then copying a script from the first scene to the second scene using the backpack. 
image

**Comment by mstoeg** [comment]
Thank you @wslany for pointing out the first issue - I'm sorry for not noticing that.

As far as the second issue is concerned, I think there is a bug in the Backpack rather than in this implementation. The problem is that broadcast messages within the backback are not copied into the new scene when they are unpacked. This already leads to vanishing messages and weird message selections in the current develop branch version (see screencast). I'm a bit confused now about how the correct behavior should actually be.

https://user-images.githubusercontent.com/60399652/103475351-c59c4a80-4dac-11eb-9f78-52ea5c7ee3e8.mp4

**Review by dandrawes — APPROVED** [review]
Looks good!

**Comment by wslany** [comment]
> As far as the second issue is concerned I fixed the issue with the freezed "edit..." messages being displayed. However, I think there is already a bug in the Backpack rather than in this implementation. The problem is that broadcast messages within the backback are not copied into the new scene when they are unpacked. This already leads to vanishing messages and weird message selections in the current develop branch version (see screencast). If this behavior is not intendet, I would suggest to add separate a bug ticket for this.

Thank you => https://jira.catrob.at/browse/CATROID-886

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
