### PR TITLE
CATROID-836 Fast user defined brick execution

### PR DESCRIPTION
**Pull request by hofcle78**
https://jira.catrob.at/browse/CATROID-836
add <with/without> screen refresh option to user defined Bricks.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by reichli — APPROVED** [review]
Looks very good now :) Thank you :+1:

**Comment by wslany** [comment]
Please also increase the Catrobat Language version number in https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/common/Constants.java#L45

**Review by wslany — CHANGES_REQUESTED** [review]
Please make sure that 
1. the alignment on the left for the <with/without> is the same as for the other lines (note: should when reversed for right-to-left languages are used, but normally Android automatically takes care of that)
2. the space between the lines <with/without> and "screen refresh as" is increased a bit, and the lower white part of the Define brick should be larger vertically
3. if possible, the triangle for the <with/without> spinner should be a bit nearer to the <with/without> text: image
4. the colors in the spinner shall be the same as those in other spinners: image 
image

**Review by reichli — APPROVED** [review]
Looks good!

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
