### PR TITLE
CAT-2676 refactoring Lego Nxt/Ev3 Brick-layouts

### PR DESCRIPTION
**Pull request by ndrnour**
also fix wrong usage of xml attributes:
* replace "fill_parent" with "match_parent"
* remove duplicated attributes "android:clickable" which already defined in the used Style.
* add missing attribute 'textDirection="locale"' to some spinners.

### CODE REVIEW

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Pull request merged**
