### PR TITLE
CAT-2156 New Graphics for Event-Bricks

### PR DESCRIPTION
**Pull request by robertriedl**
changed graphics for the correct distance between the bricks

### CODE REVIEW

**Comment by p4p4** [comment]
The first 3 commits should not be in the history, I guess?

Suggested solution:

1. `git stash`
2. `git rebase -i HEAD~4`
3. *remove the 3 lines containing the commit messages of the unwanted commits, save the file*
4. `git push -f`

This information is supplied without liability. Check history before applying step 4 ;)

**Comment by thmq** [comment]
This is not really what you should do. Have a look at [this](https://ariejan.net/2010/06/10/cherry-picking-specific-commits-from-another-branch/). That might be the operation you've been looking for. 😉

**Comment by p4p4** [comment]
of course he can do cherry-picking as well, but that would require him to create a new pull request and close this one, since he'd have to create a new branch (based on upstream/release...), or am I wrong?

**Comment by robertpainsi** [comment]
> of course he can do cherry-picking as well, but that would require him to create a new pull request and close this one, since he'd have to create a new branch (based on upstream/release...), or am I wrong?

* `git reset --hard release-0.9.27`
* `git cherry-pick c008a02`
* `git push -f`

Github doesn't care about the PR base. A branch is just a pointer to a commit. You can change the pointed commit per `git reset` (mostly used `--hard` :smirk:).

Internally, a Pull Request is just a merge. So, when merging the PR, it does following (pseudo)
* `git checkout Catrobat:release-0.9.27`
* `git merge robertriedl:CAT-FIX_SeparateEvents`

@robertriedl just created a new PR because he wanted to rename the branch :smile_cat:

**Comment by p4p4** [comment]
Although I am using all of the mentioned git commands, I did not know that it is also possible to reset to the state of another branch. Always great to learn something new, thank you! :+1:

**Pull request closed without merging**
