### PR TITLE
CAT-2604 Add icons to jumping sumo bricks

### PR DESCRIPTION
**Pull request by FlorianWeissensteiner**
#CAT-2604
https://jira.catrob.at/browse/CAT-2604

### CODE REVIEW

**Comment by FlorianWeissensteiner** [comment]
Lint issues that fail the default check are fixed here #2572

**Comment by thmq** [comment]
retest this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
ok i guess....
that IconsUtil class is hideous though... ill add a refactoring ticket in jira...

**Pull request merged**
