### PR TITLE
CATROID-750 add tabs to SpriteActivity

### PR DESCRIPTION
**Pull request by gPathpp**
Ticket: https://jira.catrob.at/browse/CATROID-750

- add tabs
- remove SpriteAttributeActivity
- refactor tests
- remove ScreenshotsForAppStore ... these "tests" are unnecessary because there are better solutions available, like placeit, etc.. (These Screenshot "tests" do not work on Develop either) 
- add NfcTagsActivity
- solve NPE issues in BottomBar

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by dandrawes — APPROVED** [review]
Well done!

**Comment by ndrnour** [comment]
good work so far, I see you took the easy way to go, which leads to completely wrong UI, this ticket isn't that easy (huge refactoring is needed), I'll post a few screenshots.

**Comment by ndrnour** [comment]
Screenshot_20201106_220247
Screenshot_20201106_220232
Screenshot_20201106_220209

**Comment by ndrnour** [comment]
as I told prof. Slany before;
> this ticket forces us to get rid of SpriteActivity.java which is the second important Activity after StageActivity in the project (it has 498 usages). currently, we rely on fragment_container in SpriteActivity to show BrickCategoryFragment, ScriptFragment, LookListFragment, SoundListFragment, NfcTagListFragment (if CATROID-749 didn't get merged) DataListFragment, ListSelectorFragment,  in simple words, all these fragments and their related usage have to be refactored.

**Comment by wslany** [comment]
Upps, I shouldn't have merged this PR. I didn't see @ndrnour 's comment because I hadn't refreshed this page since testing the PR, and didn't check the formula editor. Nur, you are of course completely right!! 

I reverted this PR with #3857. 

@gPathpp please can you correct / address Nur's comments above?

**Comment by gPathpp** [comment]
Thank you @ndrnour for detecting this mistake! You have some valid points, but instead of refactoring this huge class at once, I would suggest simply set the visibility of the tab-layout in these fragments to false. I know it's not the perfect solution, but won't stop us from merging this Ticket! Later on, we can refactor these Fragments with no Tab Layout into own activities(as I've done it with NFC). This can be done in extra (small) tickets. 
=> No big refactoring is required for this Ticket!
But unfortunately, since this PR already had been merged, I have to create a new PR.

**Pull request merged**
