### PR TITLE
Failing Junit Device Tests ~ CAT-1344

### PR DESCRIPTION
**Pull request by obusher**
Fixes all Junit Device Tests from CAT-1344 except `BroadcastActionTest.testWhenScriptRestartingItself()`.
[Test console](https://jenkins.catrob.at/job/CatroidDeviceTest/1807/console)

### CODE REVIEW

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by avihric** [comment]
@obusher you have mail :)

**Pull request closed without merging**
