### PR TITLE
Fixed Correct English capitalization  CATROID-467

### PR DESCRIPTION
**Pull request by Darshpreet2000**
Fixes CATROID-467
Fixed Correct English capitalization 

**BEFORE**
Screenshot_2020-02-22-17-20-46-24_5e2641223565f6d4087fbf5fe12dc97f

**AFTER**
Screenshot_2020-02-22-17-33-55-65_cb8aa1fae54ae6bf52051e5ffd7b0259

### CODE REVIEW

**Comment by Darshpreet2000** [comment]
Please Review my Pull Request

**Comment by PlantinumX** [comment]
pls remove Project.xml

**Comment by Darshpreet2000** [comment]
Ok

**Comment by Darshpreet2000** [comment]
I have linked another pull request
https://github.com/Catrobat/Catroid/pull/3486

**Pull request closed without merging**
