### PR TITLE
CAT-1904 Added description field expansion in program overview

### PR DESCRIPTION
**Pull request by bernadettespieler**

### CODE REVIEW

**Comment by bernadettespieler** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Comment by bernadettespieler** [comment]
green: https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/213/

**Pull request merged**
