### PR TITLE
CAT-1322 Removes till 1st index on long pressing delete

### PR DESCRIPTION
**Pull request by Achilles-96**
Fixes https://jira.catrob.at/browse/CAT-1322.

### CODE REVIEW

**Comment by Achilles-96** [comment]
Any update on this?

**Comment by fwinkelbauer** [comment]
Please run the Android Studio Formatter on your changes - like mentioned [here](https://github.com/Catrobat/Catroid/wiki/Creating-a-pull-request)

**Comment by Achilles-96** [comment]
Updated.

**Comment by Achilles-96** [comment]
Any update on this?

**Comment by thmq** [comment]
This cannot be merged automatically and should therefore be rebased. Please reopen if it's still relevant.

**Pull request closed without merging**
