### PR TITLE
Catroid-982 Adding more cases for test of maximum function

### PR DESCRIPTION
**Pull request by Aman09072000**
*Please enter a short description of your pull request and add a reference to the Jira ticket.*
https://jira.catrob.at/projects/CATROID/issues/CATROID-982
Adding More case blocks in a maximum of the Function part.
Few cases are missing when we work in the testMaximumOfFunction.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Aman09072000** [comment]
Adding More case blocks in a maximum of the Function part.
Few cases are missing when we work in the testMaximumOfFunction.

**Comment by Aman09072000** [comment]
make separate assert for each case.

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks a lot, and sorry for the delay. 

Please 
* correct the grammar in the variable name "both number is same" => "both numbers are equal" or "both numbers are the same",
* add two test cases with incorrect input (max('abc', 3) and max(sqrt(-1), 5); note that 'NaN' is the abbreviation of 'Not a number'), 
* check that there are no unneeded variables or looks in your commit,
* and squash your pull request to a single commit.

**Comment by adnaribo** [comment]
Please squash into one commit :)

**Comment by juliajulie95** [comment]
Closing PR, because no recent activity

**Pull request closed without merging**
