### PR TITLE
CATROID-1050 Missing sound bricks that should also slow down fast loops

### PR DESCRIPTION
**Pull request by frit96**
https://jira.catrob.at/browse/CATROID-1050
Added sound bricks to the slow down fast loops list

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by blindguardian50 — CHANGES_REQUESTED** [review]
Good work! However, in your Catrobat language test you are using wrong time units in the assertion bricks. The loop delay should appear after each iteration, so you would have 0.2 seconds instead of 0.02 seconds

**Comment by frit96** [comment]
Thanks for the review I somehow thought it was a delay of 0.002 seconds per iteration.
Also I noticed that either the first or last iteration doesn't count so I had to iterate 11 times for the correct delay.

**Review by blindguardian50 — APPROVED** [review]
Looks good!

**Review by petbuer — APPROVED** [review]
Thanks!

**Pull request merged**
