### PR TITLE
CAT-1655 Fix upload for restricted profile

### PR DESCRIPTION
**Pull request by 84n4n4**
Trying to log in for upload with restricted profile crashed app.
Restricted profiles are used in school classes on shared tablets.

Quickfix:
- If email returned by AccountManager is null, replace with empty
string, to prevent the null exception.

Further changes to handle arising problems:
- Automaticall invalidate TOKEN to "log out" users again right after
upload, failed upload, and canceled upload. (since without this there
is no possibility to log out to prepare tablets for next class)

Limitations:
- Not possible to register new users using a restricted profile.
- Maybe not automatically logged out if upload process is disrupted.
- Log in error messages for restricted users propably misleading,
  eg. not existing username triggers "invalid email adress" error.

### CODE REVIEW

**Comment by sjaindl** [comment]
ok to test

**Comment by robertpainsi** [comment]
Blocked by https://github.com/Catrobat/Catroid/pull/1434

**Comment by robertpainsi** [comment]
@84n4n4 When https://github.com/Catrobat/Catroid/pull/1434 has been merged, please apply your changes to the latest master.

@sjaindl :joy_cat: No Jenkins, no testrun :pensive:

**Comment by sjaindl** [comment]
@robertpainsi Hope dies last :P

**Comment by thmq** [comment]
@84n4n4 please rebase this. sorry, but had to merge release branch first.

**Pull request closed without merging**
