### PR TITLE
[CAT-2344] fix the missing resuming call of facedetection object afte…

### PR DESCRIPTION
**Pull request by manuels87**
…r a scene-change

after a scene transition the face-detection is always stopped. when the new scene is opened, the face-detection was not resumed, this caused the reported problem.

### CODE REVIEW

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
how about tests that verify correct behaviour?

**Comment by rschluesselbauer** [comment]
How would you suggest testing this @84n4n4 ?
An espresso stage test with two scenes where you check the face detection state in both scenes?

**Comment by cheidenreich** [comment]
test this please

**Comment by 84n4n4** [comment]
@rschluesselbauer 
>> An espresso stage test with two scenes where you check the face detection state in both scenes?

yeah, pretty much exactly like that....
theres a few facedetection resource tests already in the code base, check them out, and then just write a test program that switches scenes on a tap on screen, and test that.

**Pull request merged**
