### PR TITLE
CAT-2359 Fix UserListBrick/UserVariableBrick keeping old index selected when adding new list/variable

### PR DESCRIPTION
**Pull request by rschluesselbauer**
Fix spinner selection for UserListBricks and UserVariableBricks, by switching the order of if statements in both classes.
Refactor UserListBricks to use the same Touch / ItemSelected-Listeners.
Fix corresponding tests.

### CODE REVIEW

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
can you please fix the checkstyle warnings

**Comment by rschluesselbauer** [comment]
I fixed the checkstyle warnings, but now it says that merging is blocked although I have rebased the branch to be played from develop. Do you know what that is about?

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
"Merging can be performed automatically with one approved review."

**Comment by 84n4n4** [comment]
please run espresso tests

**Pull request merged**
