### PR TITLE
CAT-2270 Correcting the negative zero(-0) and positive zero(0) evaluation

### PR DESCRIPTION
**Pull request by nishantt95**
CAT-2270 Evaluating -0 = 0 to True 

Earlier -0 and 0 evaluates to False (-0 = 0 is False) and now after the correction -0 and 0 evaluates to True (-0 = 0 is True).

Note: This pull request also includes test file.

### CODE REVIEW

**Comment by robertpainsi** [comment]
LGTM! :+1:
You just need to improve your commit message header. :wink:
(https://help.github.com/articles/changing-a-commit-message/)

`CAT - 2270 Issue : earlier (-0 = 0) computes to False (CAT - 2270).`
* No spaces in the ticket identifier (before and after the minus sign `-`).
* Do not end the subject line with a period.
* You don't need to reference the ticket twice. The ticket identifier at the beginning is sufficient.
* Normally commit headers start with a verb (add, remove, fix, update, refactor, etc.). However, to me just using `Negative zero equals positive zero (-0 = 0)` is better.

→ `CAT-2270 Negative zero equals positive zero (-0 = 0)`

You can also use `CAT-2270 -0 = 0 evaluates to True`, `…is True`, or whatever you come up with.

Often it's a good idea not to use the Jira ticket title as commit message header. Like in this case. So it's great that you didn't use it. Your commit message body is also fine.

**Comment by rschluesselbauer** [comment]
+1
Looking good :-)

**Comment by robertpainsi** [comment]
commit message header !== pull request header :wink:

The commit message header is the first line of the commit message and separated by an empty newline from the body. `git log --oneline` will print the log output but only show the commit message headers.
There is a list on how to format your commit message [here](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines). Please adapt your commit message accordingly.

Both, your old and new pull request header (title) were fine. So I'm not that picky :laughing: However, your current commit message needs improvements.

**Comment by robertpainsi** [comment]
ok to test

**Pull request merged**
