### PR TITLE
REFACTROING Implemented SpriteGroup UI

### PR DESCRIPTION
**Pull request by thmq**

### CODE REVIEW

**Comment by thmq** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Pull request merged**
