### PR TITLE
CATROID-1266 Variables in backpacks removed

### PR DESCRIPTION
**Pull request by friendo97**
https://jira.catrob.at/browse/CATROID-1266

Added the removal of the scripts from the user defined bricks in the backpack.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by dandrawes — APPROVED** [review]
Made in PP!

**Review by wslany — CHANGES_REQUESTED** [review]
Please rebase, remove the conflict, and increase the year to 2022 in the third line of the (c) headers of the files contained in this PR.

**Review by wslany — CHANGES_REQUESTED** [review]
Local variables and lists shall also be added. Currently they are still deleted, see screenshots below:

Original variables and lists in scripts (note that all variables and lists are also used in formulas in bricks in scripts copied to the script-backpack, or objects copied into the object-backpack):
Screenshot_20220123-084127

After inserting the scripts from the backpack in another object, or adding a complete object from the object backpack, the local variables are incorrectly deleted, even though they still appear in the formulas of bricks in the scripts of the object:
Screenshot_20220123-083748

**Review by dandrawes — APPROVED** [review]

**Comment by wslany** [comment]
> Local variables and lists shall also be added. Currently they are still deleted, see screenshots below:
> 
> Original variables and lists in scripts (note that all variables and lists are also used in formulas in bricks in scripts copied to the script-backpack, or objects copied into the object-backpack): Screenshot_20220123-084127
> 
> After inserting the scripts from the backpack in another object, or adding a complete object from the object backpack, the local variables are incorrectly deleted, even though they still appear in the formulas of bricks in the scripts of the object: Screenshot_20220123-083748

The same error still remains: variables and lists that are local to the current object are not copied, but their names remain in the formulas.

**Comment by juliajulie95** [comment]
Please rebase

**Comment by mseiser** [comment]
Please reopen if working again, Closed due to inactivity

**Pull request closed without merging**
