### PR TITLE
CAT-1240 Update license text to 2015

### PR DESCRIPTION
**Pull request by bernadettespieler**
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Build-SourceTests-StaticChecks/969/

### CODE REVIEW

**Comment by thmq** [comment]
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/701/?auto_refresh=false

i rebased it. still something failing, but at least rebased

**Comment by robertpainsi** [comment]
Please take a look at http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html and also remove the rebased text.

I'm a little confused :confused:. git says that the two commits in this PR are merge-commits. I thought you only rebased the PR? However, this may be correct...
But I'm also missing @bernadettespieler as author or here meaningful commit message. :crying_cat_face:

**Comment by thmq** [comment]
the thing is: i did not only rebase it but also change a few things, as there were testcases failing. it should work now, yet i probably still need to look into the "UserBrickDataEditorFragmentTest.testRenameVariableEditsFormulas" although it did not fail on device.

**Comment by thmq** [comment]
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/702/

**Comment by bernadettespieler** [comment]
https://jenkins.catrob.at/job/Catroid-Build-SourceTests-StaticChecks/1025/

**Comment by avihric** [comment]
Full testrun: https://jenkins.catrob.at/job/Catroid-Multi-Job-Custom-Branch-RELOADED/707/

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Pull request closed without merging**
