### PR TITLE
CAT-2360 Right-to-Left support for Bricks

### PR DESCRIPTION
**Pull request by ndrnour**
User interface design is the most critical issue in bidirectional languages app. However, when designing for children and young people, developers often think that highly visual interface, simple interaction is the way to grab their interest. For bidirectional languages, not only does the text alignment and text reading order render from right to left, but also the UI element's layout should follow this natural direction of rendering from right to left. Of course, this layout change would only apply to localized bidirectional languages. Mirroring gives a perfect bidirectional look and feel to the UI.

### CODE REVIEW

**Comment by 84n4n4** [comment]
This branch is 3 commits ahead, 89 commits behind Catrobat:develop.

there is no way that this is mergable. please rebase and fix.

**Comment by ndrnour** [comment]
@84n4n4  89 commits behind Catrobat:develop.
capture

could you please explain that to me ?

**Comment by 84n4n4** [comment]
from our confluence: https://confluence.catrob.at/pages/viewpage.action?pageId=3965114 
2017-05-24--1495635213_624x275_scrot

https://git-scm.com/book/de/v1/Git-Branching-Rebasing

rebase

**Comment by ndrnour** [comment]
need to close

**Pull request closed without merging**
