### PR TITLE
CATROID-279 Fix unnecessary vibration

### PR DESCRIPTION
**Pull request by trummerp**
Commit 1: Quick-fix unnecessary vibration
Commit 2: Refactor some parts of VibrationUtil (For a general overhaul, I will create a separate ticket)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by christophsiegl — APPROVED** [review]
Looks good - nice rafactoring.
A mocked regression test will be added in a seperate PR?

**Comment by trummerp** [comment]
Hi, it has been quite a while since I created this PR. 
This should only be a quickfix for the vibration problem. 
@christophsiegl I think I was not able to implement a proper testcase back then. The reason is that the function, which reads the timestamps alsways returns 0, if the code is not running on a device. I could not remember the behavior on the testserver, but it was problematic with local testcases.
However, as I wrote, this should only be a quickfix and there is much more to do (See ticket description step 2-4)

**Comment by christophsiegl** [comment]
Hi, okay - good.
Thanks for the update.

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
