### PR TITLE
Cat 2403 refacturing drone, adding taking pictures and turn bricks for JumpingSumo drone

### PR DESCRIPTION
**Pull request by cpozvek**

### CODE REVIEW

**Comment by cheidenreich** [comment]
test this please

**Comment by cheidenreich** [comment]
please run espresso tests

**Comment by cheidenreich** [comment]
`org.catrobat.catroid.uiespresso.content.brick.app.JumpingSumoAnimationBrickTest.testJumpingSumoAnimationBrick` is failing

**Comment by 84n4n4** [comment]
org.catrobat.catroid.uiespresso.content.brick.app.JumpingSumoAnimationBrickTest.testJumpingSumoAnimationBricK

fails in also in develop at the moment.

theres a fix already in https://github.com/Catrobat/Catroid/pull/2540

**Pull request merged**
