### PR TITLE
CATROID-159/285 Merge Project Name And Error Check

### PR DESCRIPTION
**Pull request by Fatmangh**
This is a dialog that enables the user to enter the name of the merged project and checks for the validity of name: whether name already exists or not.

### CODE REVIEW

**Comment by ThomasSchwengler** [comment]
How is this related to CATROID-159 / #3226 ?
Does this depend on 159, or does it implement both 159 and 285?

**Comment by 84n4n4** [comment]
please squash commits

**Comment by Fatmangh** [comment]
Yeah 285 depends on 159. When the user enters the name into the dialog, 159 makes sure it is valid.

**Comment by Fatmangh** [comment]
I just squashed them all

**Comment by ThomasSchwengler** [comment]
Hey, it seems there are now three unrelated commits in this PR, did something go wrong?

**Comment by Fatmangh** [comment]
I think so and I don’t know how that happened. All of a sudden there’re over 10K commits in my forked repo, I’d don’t know if it’s because of the permission I can granted a few days ago.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Fatmangh** [comment]
I'm gonna close this and create a new one

**Pull request closed without merging**
