### PR TITLE
Merge back fixes from release branch

### PR DESCRIPTION
**Pull request by avihric**
Contains fix for 
* __CAT-1324__
* __CAT-1326__
* __CAT-1345__
* __CAT-1346__
* __CAT-1347__
* __CAT-1348__
* __CAT-1349__
* __CAT-1350__
* __CAT-1351__

### CODE REVIEW

**Comment by avihric** [comment]
ok to test

**Comment by obusher** [comment]
I think we should we wait for the `BroadcastActionTest.testWhenScriptRestartingItself` fix and then merge the `release` branch into `develop`.

**Comment by avihric** [comment]
Agree, also UserScriptActivity is in the failing list, isn't it?

**Comment by obusher** [comment]
Yes it its. There exists already an open PR (#1241)

**Comment by avihric** [comment]
ok to test

**Comment by avihric** [comment]
ok to test

**Pull request merged**
