### PR TITLE
Cat 1280

### PR DESCRIPTION
**Pull request by FlorianWeissensteiner**
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/402/

### CODE REVIEW

**Comment by obusher** [comment]
[25 tests](https://jenkins.catrob.at/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2057/testReport/) want to be fixed! :D

Please [squash](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i) your commits...

**Comment by FlorianWeissensteiner** [comment]
@obusher Sorry for the inconvenience. I will consult more advanced team-members before I submit more pull requests.

**Comment by obusher** [comment]
@FlorianWeissensteiner No problem, keep them coming! :D

**Comment by avihric** [comment]
reopen when tests fixed

**Pull request closed without merging**
