### PR TITLE
CAT-2718 Refactor NxtSensorService and EV3SensorService

### PR DESCRIPTION
**Pull request by LPeteR90**
-remove duplicate code
--merge EV3SensorService and NxtSensorService
--merge private SensorFactories from SensorService to one SensorFactory
-remove unnecessary code from EV3Sensor.Sensor and NXTSensor.Sensor
-move Lego IntDefs to Constants

### CODE REVIEW

**Comment by LPeteR90** [comment]
test this please

**Comment by LPeteR90** [comment]
test this please

**Comment by LPeteR90** [comment]
test this please

**Comment by LPeteR90** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by LPeteR90** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Pull request merged**
