### PR TITLE
CATROID-776 Redesign of formula editor

### PR DESCRIPTION
**Pull request by devsebastian**
Ticket: https://jira.catrob.at/browse/CATROID-776
### Redesign of formula editor
Redesign the editor according to the mockups

Screen-Recording-20201129-034344

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by devsebastian** [comment]
I have left the '=' button in place, this button will then be replaced by the color button in https://jira.catrob.at/browse/CATROID-782.

**Review by wslany — CHANGES_REQUESTED** [review]
The new toggle button that toggles the buttons above it shall also be in the same grey like the COMPUTE button. 

Also, it seems the lines between the buttons do not all have the same width:
image

Is it possible to have the background in white like in the mockups in the ticket? I.e., like in 
image

**Comment by devsebastian** [comment]
Sure, I thought the keyboard fragment layout might have changed a lot since the ticket was opened so left everything else (other than the buttons themselves) intact! I'll update them all and push the changes!

**Review by juliajulie95 — CHANGES_REQUESTED** [review]
FormulaEditorKeyboardTest.sensorFormulaTest does not work locally or on jenkins
Please have a look a this again

**Comment by devsebastian** [comment]
Thanks @juliajulie95, I've fixed the issue and also added the color-picker button in the current PR as discussed with @wslany on Slack! also added appropriate tests for the same. Thanks Again!

**Review by juliajulie95 — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
I think because of a new way how the color picker now needs to be called since #3900 and since that's not yet reflected in #3886 here, there's a crash when one selects the pipette in the color picker in the formula editor starting from the new color chooser button. 

Note, however, that when the color picker in the formula editor is not chosen via the button, but instead selected via the pop-up menu that appears when one taps on a color field (see below), then the pipette works fine. 
image

Here is the stack trace of the crash:
```
12-28 19:24:59.897 E/AndroidRuntime( 7397): FATAL EXCEPTION: main
12-28 19:24:59.897 E/AndroidRuntime( 7397): Process: org.catrobat.catroid.independent_20211228_1846, PID: 7397
12-28 19:24:59.897 E/AndroidRuntime( 7397): kotlin.UninitializedPropertyAccessException: lateinit property currentBitmap has not been initialized
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at org.catrobat.paintroid.colorpicker.ColorPickerDialog.access$getCurrentBitmap$p(ColorPickerDialog.kt:43)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at org.catrobat.paintroid.colorpicker.ColorPickerDialog$onCreateDialog$1$1$1.invokeSuspend(ColorPickerDialog.kt:86)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at org.catrobat.paintroid.colorpicker.ColorPickerDialog$onCreateDialog$1.onClick(ColorPickerDialog.kt:84)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.view.View.performClick(View.java:7869)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.widget.TextView.performClick(TextView.java:14958)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.view.View.performClickInternal(View.java:7838)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.view.View.access$3600(View.java:886)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.view.View$PerformClick.run(View.java:29362)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.os.Handler.handleCallback(Handler.java:883)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.os.Looper.loop(Looper.java:237)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at java.lang.reflect.Method.invoke(Native Method)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-28 19:24:59.897 E/AndroidRuntime( 7397): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): uncaughtException: 
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): kotlin.UninitializedPropertyAccessException: lateinit property currentBitmap has not been initialized
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at org.catrobat.paintroid.colorpicker.ColorPickerDialog.access$getCurrentBitmap$p(ColorPickerDialog.kt:43)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at org.catrobat.paintroid.colorpicker.ColorPickerDialog$onCreateDialog$1$1$1.invokeSuspend(ColorPickerDialog.kt:86)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at org.catrobat.paintroid.colorpicker.ColorPickerDialog$onCreateDialog$1.onClick(ColorPickerDialog.kt:84)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.view.View.performClick(View.java:7869)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.widget.TextView.performClick(TextView.java:14958)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.view.View.performClickInternal(View.java:7838)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.view.View.access$3600(View.java:886)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.view.View$PerformClick.run(View.java:29362)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.os.Handler.handleCallback(Handler.java:883)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.os.Looper.loop(Looper.java:237)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at java.lang.reflect.Method.invoke(Native Method)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-28 19:24:59.897 E/BaseExceptionHandler( 7397): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by devsebastian** [comment]
yes as suspected the crash was happening because of the addition of [#3900](https://github.com/Catrobat/Catroid/pull/3900) after this PR was created but before it was merged, I've made the necessary changes! it works fine now.

**Review by juliajulie95 — CHANGES_REQUESTED** [review]
As already discussed on slack, the current color is not used when accessing the color picker through the formula editor.
Please have a look at this.

**Review by juliajulie95 — APPROVED** [review]

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks, well done!!

**Pull request merged**
