### PR TITLE
CAT-1330 Added visible distinction for LOGIC items

### PR DESCRIPTION
**Pull request by Achilles-96**
Fixes https://jira.catrob.at/browse/CAT-1330

Signed-off-by: Raghuram Vadapalli <raghuram.vadapalli@research.iiit.ac.in>

### CODE REVIEW

**Comment by Achilles-96** [comment]
Can someone please review this.

**Comment by fwinkelbauer** [comment]
Please run the Android Studio Formatter on your changes - like mentioned [here](https://github.com/Catrobat/Catroid/wiki/Creating-a-pull-request)

**Comment by Achilles-96** [comment]
Updated.

**Comment by thmq** [comment]
This branch has conflicts hence it should be rebased and reopened if still relevant.

**Pull request closed without merging**
