### PR TITLE
Feature/raspberry

### PR DESCRIPTION
**Pull request by p4p4**
please accept my pull request. This introduces raspberry pi support.

- can be activated via build.gradle
- implements settings
- implements new Brick category
- implements 4 new Raspberry Bricks (SET pin, READ pin, PWM, when pin changed interrupt script)

### CODE REVIEW

**Comment by p4p4** [comment]
executed test (Broadcasts)
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/675/

**Comment by avihric** [comment]
Is this a feature branch? If so, a corresponding feature/raspberry branch needs to be created at Github and your PR should be made to `Catrobat:feature/raspberry`, instead of `Catrobat:develop`. ping @thmq

**Comment by avihric** [comment]
Your commit msg indicates that this is a Arduino ticket. Therefor the PR should be made onto Catrobat:feature/arduino or Catrobat:feature/arduino-firmata, dependeing which of the 2 branches is the current Arduino dev branch.
Consult @thmq and/or David Marogy

**Comment by p4p4** [comment]
Hi @avihric, thank you for pointing this out, maybe we can discuss this issue on Monday.

Yes, this is a feature branch containing (mostly) code to integrate RaspberryPi devices.

There is only one exception, namely 45b509f97c38ffe8f497b93a7429cc95a10fdf5e,  which fixes one bug concerning the Arduino feature and consists of only one line of code. I won't mix features within one pull request in the future, sorry for that ;).

**Comment by p4p4** [comment]
@thmq please create the "feature/raspberry" branch so that this request can be closed

**Comment by robertpainsi** [comment]
Here you go [feature/raspberry](https://github.com/Catrobat/Catroid/tree/feature/raspberry) :wink:

**Pull request closed without merging**
