### PR TITLE
CATROID-1349 Catrobat Language Test for RepeatUntil_IsTrue control.

### PR DESCRIPTION
**Pull request by Anshul-9923**
I created a Catrobat Language Test for Repeat Until ___ is True function which is present in the controls section.

https://jira.catrob.at/browse/CATROID-1349
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [X] Include the name of the Jira ticket in the PR’s title
- [X] Include a summary of the changes plus the relevant context
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [X] Include reasonable and readable tests verifying the added or changed behavior
- [X] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Stick to the project’s gitflow workflow
- [X] Verify that your changes do not have any conflicts with the base branch
- [X] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Anshul-9923** [comment]
@wslany Please review my code for the Jira issue https://jira.catrob.at/browse/CATROID-1349.

**Comment by Anshul-9923** [comment]
@wslany Do I need to make any changes to my PR? Please let me know if is there.

**Comment by Anshul-9923** [comment]
@juliajulie95 Please review my code for the Jira issue https://jira.catrob.at/browse/CATROID-1349. I created this issue as told in first training tickethttps://jira.catrob.at/browse/CATROID-390.

**Comment by Anshul-9923** [comment]
@dmetzner Can you please review my code?

**Comment by dmetzner** [comment]
@Anshul-9923 There is not much code in this PR for me to review. Comparing it to previous similar PRs, such as https://github.com/Catrobat/Catroid/pull/4318, I would guess your approach seems to be right ;)

I keep the analysis of your catrobat project to our Pocket Code PROs, like @wslany :)

**Comment by Anshul-9923** [comment]
@dmetzner I wanted to start contributing to Catrobat. But I guess I can't do so until my first training ticket PR will be merged which is to create a Catrobat Language Test. So, I am waiting for the merging of my PR.

**Comment by dmetzner** [comment]
@Anshul-9923 You can always start to contribute in any way you prefer! Catrobat is an OpenSource project. Every contribution counts. Of course, it is always nice to finish some Jira tickets if possible, since those tickets are well described and prioritized. Such "training" tickets should only help you get started with the project. However, if you have any improvements or ideas feel free to implement them. :)

**Comment by Anshul-9923** [comment]
> @Anshul-9923 You can always start to contribute in any way you prefer! Catrobat is an OpenSource project. Every contribution counts. Of course, it is always nice to finish some Jira tickets if possible, since those tickets are well described and prioritized. Such "training" tickets should only help you get started with the project. So if you have any improvements or ideas feel free to implement them. :)

I want to work on some Jira issues of the Paintroid project but am not able to claim them.

**Comment by dmetzner** [comment]
I should have the rights to do this - just show me the ticket :)

**Comment by Anshul-9923** [comment]
> I should have the rights to do this - just show me the ticket :)
This is the link for the Jira issue, I have also asked to assign me this issue but didn't receive any response.
https://jira.catrob.at/browse/PAINTROID-343

**Comment by dmetzner** [comment]
I can only assign it to me... However this way no one is going to steal it from you in the meantime :)

**Comment by Anshul-9923** [comment]
> I can only assign it to me... However, this way no one is going to "steal" it from you in the meantime :)

Do you know how can I assign it to me?

**Comment by Anshul-9923** [comment]
Hi @petbuer Can you please review my code?
PR Link: https://github.com/Catrobat/Catroid/pull/4432

**Comment by Anshul-9923** [comment]
@wslany I want to start contributing by resolving some issues of the Paintroid project but am not able to do so until I think my first training ticket PR will get merged. Please review my code that's all I can say.

**Comment by juliajulie95** [comment]
Dear @Anshul-9923,
I contacted the coordinator of Paintroid to send you a message,
also I posted your PR in our slack workspace and someone will review it soon.
I assigned the CLT ticket to me to block it for you, but you will gain board permissions after you did some tickets for us :)
Thank you for contributing to our project!

**Comment by Anshul-9923** [comment]
> Dear @Anshul-9923, I contacted the coordinator of Paintroid to send you a message, also I posted your PR in our slack workspace and someone will review it soon. I assigned the CLT ticket to me to block it for you, but you will gain board permissions after you did some tickets for us :) Thank you for contributing to our project!

Thanks a lot @juliajulie95

**Review by Walcho1125 — CHANGES_REQUESTED** [review]
Thank you for your contribution, here a few points to change in your PR: 

- Please put the test file into an appropriate folder and not into the root folder... e.g.: **catroid\src\androidTest\assets\catrobatTests\bricks\control** (as it is a control brick)

- Please match the project name with the testname (yours is named after the default projectname)

- Your test is not considered a catrobat test, as it is not possible to run it automatically. To be tested automatically please use the test bricks (activate them by checking Settings/Testing extension in the app).

**Comment by Walcho1125** [comment]
@Anshul-9923 please take a look at the wiki entry on [how to do catrobat language tests](https://github.com/Catrobat/Catroid/wiki/How-to-do-Catrobat-language-tests)

**Comment by Anshul-9923** [comment]
> I created a Catrobat Language Test for Repeat Until ___ is True function which is present in the controls section.

Thanks for this. I understood how to write CLT and wrote CLT for the Item Index function.
PR Link: https://github.com/Catrobat/Catroid/pull/4456

**Pull request closed without merging**
