### PR TITLE
CAT-1154 Added Dialog for new Sound File:

### PR DESCRIPTION
**Pull request by loibi93**
https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2269/

All Tests pass, except for the setLookBrickTest which always fails !

### CODE REVIEW

**Comment by thmq** [comment]
I'm starting to feel sorry for saying this again, but please refactor your commit message to something more concise. e.g.: 

```
CAT-1154 Added Dialog for new Sound File:
now possible to choose between file and sound recorder,
fixed return to ScriptFragment
```

or something in that manner. Thank you.

**Comment by loibi93** [comment]
No problem ;D

**Comment by thmq** [comment]
Perfect! Thank you very much! We can give it a final review tomorrow then it should be good to merge.

**Comment by thmq** [comment]
ok to test

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/451/

Rerun of failed Test. SetLookBrickTest failed as always...

**Comment by thmq** [comment]
I started another test run yesterday too, where 15 tests failed [1], could you look into that, please?

[1] https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/2275/#showFailuresLink

**Comment by loibi93** [comment]
I already saw that, it seams that (for some reason, most likely a timing issue wit robotium) the ClearGraphicEffectTest failed, and when you have a look at the other tests, they fail all for similar reasons (could not find XYZ). This happens sometimes, when a test fails, and the device (or emulator) are stuck on the current view, so all following tests fail, because they don't find the view where they are supposed to start ! I think this happens because tearDown is not called correctly, but as you saw, a rerun of the tests was nearly clean, so i really don't think that these tests failed because of my implementation.

**Pull request merged**
