### PR TITLE
CAT-1601 Single and multi-touch sensors

### PR DESCRIPTION
**Pull request by p4p4**
reopened https://github.com/Catrobat/Catroid/pull/1663 after code review.
Code review done - ready to merge.

___________

Implemented CAT-1608 CAT-1609 and CAT-1610 (Single and Multi-Touch), which are sub-tasks of CAT-1601

When screen is touched:

    is a new head brick
    executed whenever the screen is touched

Single Touch description:

    screen_touch_x and screen_touch_y return the coordinates of the last touch
    screen_is_touched returns 1 when the last touch on the display is still active

Multi Touch description:

    screen_touch_x ( i ), screen_touch_y ( i ), screen_is_touched ( i ) parametrized
    index i is 1 for the first touch and increases after each new touch, until the project is restarted
    last_screen_touch_index returns the index of the last touch
    screen_touch_x ( i ) und screen_touch_y ( i ) preserve there values, even when screen_is_touched ( i ) is false again.

test-program:
https://dl.dropboxusercontent.com/u/961915/catroid-multitouch/multitouch%20test%20neu.zip

### CODE REVIEW

**Comment by Bioxar** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Comment by Bioxar** [comment]
There are four checkstyle warings: [[1]](https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidTriggerPullRequestTest/224/)

**Comment by p4p4** [comment]
@Bioxar fixed, thanks for reporting. Those nasty empty lines...

**Comment by p4p4** [comment]
TESTS:
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/219/

**Comment by thmq** [comment]
please rebase and reopen when done.

**Pull request closed without merging**
