### PR TITLE
[Accessabilty] Changed to AppCompat resources and styles

### PR DESCRIPTION
**Pull request by thmq**

### CODE REVIEW

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Pull request merged**
