### PR TITLE
[Cat 2579] Update ARDrone2.0 bricks and xml to the current project standard

### PR DESCRIPTION
**Pull request by dkienreich**

### CODE REVIEW

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by dkienreich** [comment]
please run espresso tests

**Comment by dkienreich** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please resolve conflicts and align with nur on which one should be merged first.
https://github.com/Catrobat/Catroid/pull/2587
or yours

**Comment by dkienreich** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
can you guys please let me know which is better to merge first:
https://github.com/Catrobat/Catroid/pull/2587
https://github.com/Catrobat/Catroid/pull/2558

**Comment by ndrnour** [comment]
@dkienreich could you please finish your task in order to finish later my PR #2587 which is on hold waiting for your PR to get merged.

**Comment by dkienreich** [comment]
for me it is fine, if this ticket will be merged first

**Pull request merged**
