### PR TITLE
CATROID-1223 Implemented done and play button in Formula Editor

### PR DESCRIPTION
**Pull request by dorianpercic**
https://jira.catrob.at/browse/CATROID-1223
Implemented "done" and "play" button in Formula Editor. Replaced "compute" button with these 2 buttons.
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by bengaal** [comment]
Please rebase the branch!

**Review by bengaal — CHANGES_REQUESTED** [review]

**Comment by bengaal** [comment]
It also appears, that there are some new tests failing which are not present at the run of the develop branch. If the rebase doesn't solve the issue, please make sure to fix them as well.

**Comment by dorianpercic** [comment]
> It also appears, that there are some new tests failing which are not present at the run of the develop branch. If the rebase doesn't solve the issue, please make sure to fix them as well.

Thank you for the review, I implemented every suggestion of you.
Regarding the failing tests: I fixed every test, except "testFailParse". I tried for several hours, but it just does not work out. The test is also marked as flaky already, so I think it might also fail on develop, but not always. For this test we should create a new ticket imo. What do you say?

**Comment by bengaal** [comment]
> 

If you add 
```Java
		onView(withText(R.string.yes))
				.inRoot(isDialog())
				.check(matches(isDisplayed()))
				.perform(click());
```
after `FormulaEditorFragmentTest.java#L116` the test appears to pass locally. Adding the call is also necessary from the test's point of view, since otherwise the user-journey is not up to date anymore, the test is stuck.

**Comment by bengaal** [comment]
Pull request migrated to: https://github.com/Catrobat/Catroid/pull/4678

**Pull request closed without merging**
