### PR TITLE
CAT-2361 Fix wrong rotation for rotation style "left-right"

### PR DESCRIPTION
**Pull request by rschluesselbauer**

### CODE REVIEW

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
on the left screen bounce it still does something odd. for the first two look switches or so, the orientation stays the same while direction of movement has changed already.
kind of looks similar to what it looked like before this fix, but now for the short period it did switch before, it does not switch now...

**Comment by rschluesselbauer** [comment]
Seemed to happen with very few specific step sizes - should be fixed :)

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
test this please

**Pull request merged**
