### PR TITLE
CATROID-1009 fixed testCurrentProjectAfterDownload

### PR DESCRIPTION
**Pull request by ISKalsi**
Ticket: https://jira.catrob.at/browse/CATROID-1009

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by mstoeg — CHANGES_REQUESTED** [review]
The main problem with this testcase is that the project `downloadedProject` is not deleted in the first place. With your approach you circumvented this by deleting the concering project during set up. I would recommend to tackle the root of this problem: When `deleteProjects()` is called at the end of the testcase in `tearDown()` the Project `downloadedProject` is still open - thus it cannot be deleted and remains stored. My suggestion would therefore be to close the project before calling `tearDown()`. Just adding the lines 
`pressBack();`
`onView(withText(R.string.main_menu_programs)).perform(click());` 
at the end of the testcase `testCurrentProjectAfterDownload()` should do the trick.

**Comment by ISKalsi** [comment]
Ohh, I kept finding a problem with Testutils and failed to notice that it would be that simple. Thanks!
Please review the updated PR.

**Review by mstoeg — APPROVED** [review]
Looks good now!

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
