### PR TITLE
CAT-1441 Move setHasOptionsMenu call to onActivityCreated

### PR DESCRIPTION
**Pull request by FlorianWeissensteiner**
https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/397/

### CODE REVIEW

**Comment by thmq** [comment]
why did you only run a single class and package test?

**Comment by obusher** [comment]
[Single-test-run](https://jenkins.catrob.at/view/All-Categories/view/Catroid/job/Catroid-CustomEmulator-Single-ClassAndPackage-Test/401/) of failing testcase is green.

**Comment by obusher** [comment]
@thmq Click the red cross and you access the full test-run.

**Comment by obusher** [comment]
@Catrobat/catroid @Catrobat/contributors Can someone with a Nexus S API 16 verify this PR? [(CAT-1441)](https://jira.catrob.at/browse/CAT-1441)

**Comment by Manu91** [comment]
I have tested it on a Nexus S API 16 and it works now.

**Comment by obusher** [comment]
@Manu91 TYVM! ;)

**Pull request merged**
