### PR TITLE
Fix RTL and LTR alignment mentioned in note in CATROID-1203

### PR DESCRIPTION
**Pull request by sahil9001**
Fixed the `textAlignment` to change according to the language specified.

This was mentioned as a note in https://jira.catrob.at/projects/CATROID/issues/CATROID-1203, and is here fixed for the three-line parameter fields of the "Assert" brick, as of https://jira.catrob.at/browse/CATROID-1086 implemented in #4239.

Before the change:

Centered text

After the change:

English LTR
Arabic RTL

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by sahil9001** [comment]
@wslany

**Comment by wslany** [comment]
Thanks @sahil9001 --- I merged this without code review since it was simple. 

Note, however, that this PR is not resolving https://jira.catrob.at/browse/CATROID-1203 --- the latter suggests to do this for _all_ bricks, but at this time is still under discussion (that is why the ticket currently is still marked as WIP), because we need to think about how to solve the issue that vertically-large bricks that have many parameter fields already may become very long vertically. There is especially the issue of how it will look like in the formula editor, in particular on small screens. This is already even now a problem for large bricks, so the question is, is there a good way to handle it? Maybe have a way to collapse bricks in the formula editor, or even make the brick at the top vanish completely, i.e., expand the edit field towards the top, depending on the user whishes? Another idea would be to make the brick at the top of the formula editor scrollable. If you have any good ideas, let me know.

**Comment by sahil9001** [comment]
@wslany I guess that making it scrollable would make much more sense rather than collapsing it to the top of the screen, in that way the user would be able to navigate through the edit text as well as scroll up to the mark where he/she is typing. Also, I am unable to join Slack of this community, is there a mark to qualify for that?

**Comment by wslany** [comment]
Dear @sahil9001 , Catrobat's UX team will discuss this next week and hopefully come up with a solution. 

Two things that bother me with the formula editor too, and maybe you could find a solution or at least create new bug tickets for it, is that (a) currently the parameter fields in the bricks at the top do not update while on changes the formula in the edit window below, and that (b) spinners do not work in the brick at the top. Both would be awesome, or also just one of them. Please let me know whether that would be of interest to you. Note that we would also need tests for fixes and in PRs. 

Regarding Slack, we have a limited professional admin account, so the number of active users is capped. We are currently skimming it, so we limit the number of people to non-casual contributors. There's an onboarding procedure, and the first steps are described on the README.md file of the repo of the corresponding sub-project of Catrobat on github, e.g., Catroid's. 

Having said that, I saw that you have contributed already to several tickets. Since it was outside of the normal workflow, I didn't track it correctly so far, but I just saw that there were quite a few. Some comments haven't been resolved yet, e.g., for #4203 --- could you have a look at that so we can finish it? 

I am of course ready to add you to our regular contributors team including to Slack if you are interested and willing to invest some time in Catrobat, and complete two first steps, namely send me a link to a user-project you created with Pocket Code, and created a ticket for a Catrobat Language Test as described on the README.md page for Catroid. I'll then give you a few more instructions and videos to watch in a telco. Please contact me at wolfgang.slany@catrobat.org for setting up everything. Thanks a lot!

**Pull request merged**
