### PR TITLE
CAT-1361 Undo/Redo in Sprites, Looks, Sounds and NFCTags

### PR DESCRIPTION
**Pull request by loibi93**

### CODE REVIEW

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
Can this be merged now ? @thmq

**Comment by loibi93** [comment]
ok to test

**Comment by loibi93** [comment]
Branch is rebased and squashed to one commit, testruns are good, UX has approved it, and also the code review has been done, I think this one is good to go !

CatroidCheck: https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/216/
CatroidSinglePackageEmulatorTest: https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidSinglePackageEmulatorTest/1801/

**Comment by thmq** [comment]
ok to test

**Pull request closed without merging**
