### PR TITLE
CATROID-504 Project is not saved

### PR DESCRIPTION
**Pull request by dmetzner**
-  based on the work of @Pratik1999
- saves changes to new projects after its upload.

https://jira.catrob.at/browse/CATROID-504

This PR is basically just a rebase and squash with minor fixes of PR https://github.com/Catrobat/Catroid/pull/3556 which was based on https://github.com/Catrobat/Catroid/pull/3553 since a hotfix would be necessary to be released as soon as possible.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Pratik1999** [comment]
[https://github.com/Catrobat/Catroid/pull/3553](url)
this was the original pull request for the issue

**Comment by wslany** [comment]
> #3553
> this was the original pull request for the issue

Thanks for this! Are you interested in contributing more?

**Comment by Pratik1999** [comment]
> > #3553
> > this was the original pull request for the issue
> 
> Thanks for this! Are you interested in contributing more?

Yes, obviously I will be contributing to Catroid.

**Comment by wslany** [comment]
Thanks, also to @Pratik1999  !!

**Pull request merged**
