### PR TITLE
CATROID-808 "Open __URL__ in browser" brick

### PR DESCRIPTION
**Pull request by devsebastian**
Ticket: https://jira.catrob.at/browse/CATROID-808

### "Open __URL__ in browser" brick
Added Open Url Brick, which will open the given URL in a browser if it has been added to the allowed domains, otherwise shows the dialog asking for permission.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by wslany** [comment]
Please fix the lint warning https://jenkins.catrob.at/job/Catroid/job/PR-3882/2/analysis/

**Review by wslany — CHANGES_REQUESTED** [review]
Awesome!

Please increase the Catrobat language version in https://github.com/Catrobat/Catroid/blob/develop/catroid/src/main/java/org/catrobat/catroid/common/Constants.java#L42 (please do not increase to 1.0 --- this is reserved to when the user-defined brick functionality is merged, which hopefully will be very soon).

**Comment by wslany** [comment]
And please also add an entry for the "Help" url for this brick in catroid/src/androidTest/java/org/catrobat/catroid/test/BricksHelpUrlTest.java --- thanks!

**Review by wslany — APPROVED** [review]

**Review by Rawbat — CHANGES_REQUESTED** [review]
Looks good, but please add the brick to the BrickCategoryTest, the RtlBrickTest, BackwardCompatibleCatrobatLanguageXStream and the XstreamSerializer.
The BrickCategoryTest and BrickXmlSerializerTest even fail right now because of this.

**Review by Rawbat — APPROVED** [review]
Looks good, thanks!

**Review by wslany — CHANGES_REQUESTED** [review]
Nice! However, please fix the *crash* that happens when the request to open an untrusted web page (e.g., https://krone.at ) is *denied* by the user. The other web bricks, such as "Send web request to", do not lead to such a crash when the request is denied. Instead, in that case the brick shall simply be skipped once, in this case, but only once - the next time, the question should come again, even with the same web page and during the same ongoing execution.

**Comment by devsebastian** [comment]
Sorry about that, was being caused due to a toast message on (HTTP) error, I assume no toast must be display in this case as no network call is supposed to be made, it should just skip to the next brick. Have made the necessary change! Thanks.

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
