### PR TITLE
right-to-lift Bricks test

### PR DESCRIPTION
**Pull request by ndrnour**
related to **CAT-2360** Right-to-Left support for Bricks

### CODE REVIEW

**Comment by ndrnour** [comment]
@84n4n4 could you please review the test, thanks.

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by ndrnour** [comment]
@84n4n4  noch mal bitte!
danke,

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
hi!

is merged!

danke!!
ciao!
hirschi

**Pull request merged**
