### PR TITLE
CATROID-1310 Redesign of the create project dialog

### PR DESCRIPTION
**Pull request by Piki2000**
https://jira.catrob.at/browse/CATROID-1310

- added disable of confirm button, when new project name already exists

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by dandrawes — APPROVED** [review]
Well done!

**Review by wslany — CHANGES_REQUESTED** [review]
Please change so that the default name is selected and the keyboard shown:

Currently no keyboard, no pre-selected name of new project:
image

Please change to immediately let the keyboard appear, with the suggested name already fully selected, like this:
image

**Comment by wslany** [comment]
Please increase the padding between symbols and radio buttons, and please add the (translatable resource) strings "Portrait" and "Landscape" below the corresponding icons. Balance vertical spacing/padding accordingly to compensate for the increased vertical place needed for the icons with the text below. 
image

**Review by dorianpercic — APPROVED** [review]
LGTM!

**Pull request merged**
