### PR TITLE
Summary Text Of Language Setting

### PR DESCRIPTION
**Pull request by ndrnour**
As Prof. Slany recommended:
change the text of language description to "select the Language of the App"

### CODE REVIEW

**Comment by 84n4n4** [comment]
can you please put this PR against the release0.9.32 branch, since i guess wolfgang wants to have this in the upcoming release...

**Comment by ndrnour** [comment]
@84n4n4 I have no Idea how to do that! 
do you mean to push it to release-0.9.32 branch?

**Comment by 84n4n4** [comment]
ah, i just saw that i can do that on your PR.

its what is called the "base" for the PR, when you open a new one, you get this 4 dropdowns, on the left side the base repository and the base branch, there you can choose something different than "develop"...

**Comment by ndrnour** [comment]
thanks for the explanation

**Pull request merged**
