### PR TITLE
CATROID-1005 FATAL EXCEPTION: androidx.test.espresso.NoMatchingViewException

### PR DESCRIPTION
**Pull request by bengaal**
[CATROID-1005](https://jira.catrob.at/browse/CATROID-1005)

Problem was: in many cases the entered string was truncated due to
too fast automated typing. Modify type string method to use replaceText
instead of doing them sequentially, since that way they might collide
with each other.
Another problem was: an alert message popped up that the string might
be a formula. This now gets dismissed if it pops up.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by petbuer — APPROVED** [review]
Thank you!

**Review by juliajulie95 — CHANGES_REQUESTED** [review]
org.catrobat.catroid.test.ui.BrickSearchTest.testCategorySearch still fails on jenkins, please have a look

**Comment by bengaal** [comment]
@juliajulie95 This issue has been resolved in PR https://github.com/Catrobat/Catroid/pull/4321 (https://jira.catrob.at/browse/CATROID-1219)

**Comment by juliajulie95** [comment]
Please rebase

**Comment by adnaribo** [comment]
Looks good. Thank you

**Review by adnaribo — APPROVED** [review]

**Review by juliajulie95 — APPROVED** [review]

**Pull request merged**
