### PR TITLE
CATROID-857 Change Dialog for exiting Visual Placement

### PR DESCRIPTION
**Pull request by Khushi-24**
**Description**
"Cancel" button renamed to "Discard"

**Jira Ticket Reference: https://jira.catrob.at/browse/CATROID-857**

Attached Screenshot:
Screenshot (168)

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
-  Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by wslany** [comment]
Thanks @Khushi-24 , please resolve the conflict and squash the PR into one commit.

**Review by wslany — CHANGES_REQUESTED** [review]
Sorry, these strings must still remain as translatable resources so they can be localized to the user's language.

**Comment by Khushi-24** [comment]
Thanks, Sir, I got it that we can't directly change the text on buttons as the application supports different languages. I need to make some further changes in the string.xml file and add the respective text as per the language. It would take some time. I will complete it as soon as possible as per the requirements.

**Comment by wslany** [comment]
Ahh, sorry, I didn't see this. Please only add the main English strings. The rest will be translated by the translators (including you if you want) via https://translate.catrobat.org/ once the ticket has been merged. No need to add them in the pull request, since they will be overwritten here once the translations are imported from https://translate.catrobat.org/ --- sorry and thanks, and all the best for 2021!!

**Comment by Khushi-24** [comment]
Thank You, Sir
What about the conflicting files, sir? Do I need to resolve it? If so then I am not having access to resolve the conflicts. As I can see the person who was earlier working on the ticket might have changed the string to cancel. As the present version of the pocket code consists of Yes and No for Saving the changes option.

**Comment by wslany** [comment]
Please rebase your fork via git, then resolve the conflict locally and push to your PR. Thanks!

**Pull request closed without merging**
