### PR TITLE
CATROID-192 Play note X for Y beats

### PR DESCRIPTION
**Pull request by Rawbat**
Created a notpicker dialog and view for picking a single note as secondary option to the formula editor and included it for this brick. Added note value display on the piano view and implemented adjusted note value playing in the note picking view. Also includes a fix for storing created midi sound files by changing their storage location to the default sound directory of a scene

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by adnaribo — APPROVED** [review]
Looks good to me!

**Review by wslany — CHANGES_REQUESTED** [review]
Please make sure the behaviour is like in Scratch. See https://en.scratch-wiki.info/wiki/Play_Note_()_for_()_Beats_(block) for details, and test in https://scratch.mit.edu/ by adding music bricks via 
image
and there then 
image
leading to 
image

**Review by adnaribo — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Very nice!

Please increase CURRENT_CATROBAT_LANGUAGE_VERSION in catroid/src/main/java/org/catrobat/catroid/common/Constants.java

In the brick selection menu, please move the brick up, so that it is below the "Set instrument to" brick:
image

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
