### PR TITLE
Refactoring of [G|g]hostEffect to [T|t]ransparency.

### PR DESCRIPTION
**Pull request by obusher**
* Refactoring of all occurrences of `[G|g]hostEffect` to `[T|t]ransparency`.
* Update of `CatrobatLanguageVersion` to `0.95` + junit test.

Deprecated PR: #1110 .

### CODE REVIEW

**Comment by obusher** [comment]
Label: XML-Change!

**Comment by obusher** [comment]
This branch got some fresh update and wants to get merged fast into `develop`!
[Test Green] (https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1068/)

The squashing triggered a new PR-Testrun. :ghost:

**Comment by avihric** [comment]
Remove catroid/res/values-it/strings.xml, as this is handled by Crowdin. Thanks.

**Comment by obusher** [comment]
Updated... :gem: 
[Test Green] (https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/1184/)

**Comment by avihric** [comment]
ok to test

**Pull request merged**
