### PR TITLE
CAT-1161: Added Floor and Ceil functions along with tests.

### PR DESCRIPTION
**Pull request by KKcorps**
Hi Sir,
I have squashed all my commits into a single one and have made necessary changes to remove the conflicts.Please review my PR and let me know in case any other changes are to be made.
Here's the link to my previous [PR](https://github.com/Catrobat/Catroid/pull/1190)

### CODE REVIEW

**Comment by obusher** [comment]
ok to test

**Comment by KKcorps** [comment]
Can anyone please tell me what are these failed checks?

**Comment by obusher** [comment]
ok to test

**Comment by avihric** [comment]
Hi @KKcorps the test taht failed was random and not caused by your changes, but 
I would have a request that you undo the changes in 'catroid/res/values-de/strings.xml'

This is going to be handled by our trasnlation platform, so therefor only 'catroid/res/values/strings.xml' needs to be changed.

**Comment by KKcorps** [comment]
Hi @avihric , 
I've removed the german translations.Please review the request now.

**Comment by avihric** [comment]
I did already. Please have some more patience until next week, as we discovered some critical problems and need to fix them.

**Comment by KKcorps** [comment]
Sure.

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
ok to test

**Comment by obusher** [comment]
@KKcorps Please rebase onto `upstream/develop` and squash your commits again into one. 
Thank you! :dancer:

**Pull request closed without merging**
