### PR TITLE
CAT-909 Delete multiselection at rename objects

### PR DESCRIPTION
**Pull request by LauraBebek**

### CODE REVIEW

**Comment by avihric** [comment]
:two: checkstyle warnings

**Comment by LauraBebek** [comment]
fixed checkstyle warnings :)

**Comment by avihric** [comment]
retest this please

**Comment by avihric** [comment]
retest this please

**Comment by wslany** [comment]
Question: How will a Rename then be possible via the "three-dots" menu in the action bar? Remember that almost all users do not know about long press. If renaming is not possible via the menu, then we need a hint about the long press to educate users about it.

**Comment by LauraBebek** [comment]
Rename via the "three-dots" menu is still possible, only the multiselection when rename already is chosen is removed
https://jira.catrob.at/browse/CAT-909

Have to wait for jenkins with restesting.

**Comment by thmq** [comment]
please rebase this.

**Pull request merged**
