### PR TITLE
Merge Feature Lego_ev3 into develop 

### PR DESCRIPTION
**Pull request by MightyMendor**
This pull request is considered as the release of the Ev3 feature, future changes regarding EV3 should be handled directly with the develop branch, so the feature/lego_ev3 branch will no longer be needed after this merge.

This includes the two epics 
- CAT-1365 Implement Basic Functionality of EV3
- CAT-1407 Sensor Implementation for Ev3
  and all tickets assigned to these two epics.

Additional tickets regarding Bugfixes / Improvements:
- CAT-1391 
- CAT-1872

### CODE REVIEW

**Comment by thmq** [comment]
ok to test

**Comment by fwinkelbauer** [comment]
please fix conflicts and reopen when done

**Comment by MightyMendor** [comment]
Copied comment by Thomas Hirsch from the other pull-request (#1782):

here the test results of the nightly uitest run:
https://jenkins.catrob.at/view/LeeroyMultiJobs/job/CatroidEmulatorAllTestsSerialNightly/46/testReport/

in comparison to the nights before testrun on develop branch, these have been fixed:
org.catrobat.catroid.uitest.content.brick.ChangeColorByNBrickTest.testChangeColor 
org.catrobat.catroid.uitest.ui.activity.ScriptActivityTest.testPlayProgramButton 
org.catrobat.catroid.uitest.ui.activity.MyProjectsActivityTest.testScreenshotUpdate 
org.catrobat.catroid.uitest.ui.activity.ProjectActivityTest.testAddNewSprite 
org.catrobat.catroid.uitest.ui.activity.ProjectActivityTest.testNewSpriteDialog 
org.catrobat.catroid.uitest.ui.fragment.ScriptFragmentTest.testBackPackAndUnPackFromDifferentProgrammes 

these are now newly broken for some reason:
org.catrobat.catroid.uitest.formulaeditor.FormulaEditorDataFragmentListTest.testAddUserListAfterStage
org.catrobat.catroid.uitest.ui.activity.ProjectActivityTest.testAddedSpriteVisibleOnLongList 
uitest.web - some tests here, but most due to internet connection error?

_________________________________________________________________________________

I looked into some of these tests and none seem to have anything to do with the changes within the Lego-Implementation. 

Also the outcome of the tests (I looked into) is the same for the develop branch and the feature_ev3 branch.

For example the mentioned test uitest.formulaeditor.FormulaEditorDataFragmentListTest.testAddUserListAfterStage seem to pass on jenkins on both branches, when started individually, but not within the nightly testrun.
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidSingleClassEmulatorTest/74/testReport/
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidSingleClassEmulatorTest/75/testReport/

**Comment by MightyMendor** [comment]
Another example I looked into: 
uitest.formulaeditor.FormulaEditorDataFragmentListTest.testKeyCodeBackOnContextMode 

I don't really know how this part of pocketcode should work! 

While deleting variables in the formulaeditor there is a dialog(warning) to confirm the deletion when pressing back (cell-phone navigation), which seems strange to me (back does the same as the confirm-button in top left corner?). This seems not to be handled by the testcase. 
(Testcase: check check-boxes to delete variables -> go back -> check if variable were falsely deleted) 

What to do with that information? Create jira-ticket?

**Pull request merged**
