### PR TITLE
move Strings to Strings-XML

### PR DESCRIPTION
**Pull request by Gorphi**

### CODE REVIEW

**Comment by robertpainsi** [comment]
Please translate the new strings into German!

**Comment by avihric** [comment]
Well for tranlation we use [Crowdin](https://crowdin.com) now. So english strings should be sufficient once #1147 is merged.

**Comment by robertpainsi** [comment]
Ah, thanks for info :smile_cat:
Will be merged tomorrow... with caution! :scream_cat:

**Comment by avihric** [comment]
@robertpainsi @Gorphi  Please rebase to master, as I have merged #1158 which has many fixes.

**Pull request merged**
