### PR TITLE
CAT-1915 FE redesign Subcategories

### PR DESCRIPTION
**Pull request by bernadettespieler**

### CODE REVIEW

**Comment by bernadettespieler** [comment]
please retest this

**Comment by bernadettespieler** [comment]
ok to test

**Comment by Bioxar** [comment]
FM: You haven´t changed the name from "Sensors" to "Device".

**Comment by thmq** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Comment by Bioxar** [comment]
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/201/  please fix this

**Comment by Bioxar** [comment]
ok to test

**Comment by thmq** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Comment by Bioxar** [comment]
ok to test

**Pull request merged**
