### PR TITLE
CATROID-773 Upload unmodifed example project

### PR DESCRIPTION
**Pull request by MohamedMedhat1998**
*Please enter a short description of your pull request and add a reference to the Jira ticket.*  

Prevented uploading unmodified example projects from the options menu.  

#### Before
1) Create a new example project.
2) Go to upload action
3) optional - add description
4) click "Next" button

You can't upload it. But there is no error only an information text (easy to miss). Besides, the whole text fields and NEXT are not working anymore.

Feels like the app just crasht. 
#### After
Better usability.

1) Create a new example project.
2) Can't go to upload section

A click on the upload button should create a snackbar error, stating it is not possible to upload an unmodified project. 
#### Note
After clicking upload from the options menu, the app freezes for a moment. Seems like it is because of the `isDefaultProject` check.
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by aried3r** [comment]
Hey @MohamedMedhat1998, I'm no longer actively involved with this project so I'm afraid I cannot help you with a code review.

I believe some of the others you mentioned may also no longer be involved.

**Comment by sjaindl** [comment]
@MohamedMedhat1998 Seems you basically pinged all the "old veterans" :)
I'm also not actively involved atm, so I'm afraid I also can't help you with a review here.

**Comment by MohamedMedhat1998** [comment]
@wslany Hello Sir, I hope you are still working on the project.  
Can you please review this PR?

**Review by ndrnour — CHANGES_REQUESTED** [review]
please rebase and fix the conflicts, then I'll have a look

**Comment by juliajulie95** [comment]
@MohamedMedhat1998 Are you still working on this?

**Comment by MohamedMedhat1998** [comment]
@juliajulie95 No, you can work on this if you are interested.

**Pull request closed without merging**
