### PR TITLE
Libgdx 1.2.0 Update

### PR DESCRIPTION
**Pull request by anderth88**
This branch contains an update of the libgdx library to Version 1.2.0.
As from now it will be possible to change the libgdx Version by changing the gdxVersion value in the project's build.gradle file.

### CODE REVIEW

**Comment by avihric** [comment]
Please rebase to master and squash your commits.

**Comment by aried3r** [comment]
libdgx 1.5.4 ist the latest version, fyi.

**Comment by obusher** [comment]
#1174

**Comment by linsm** [comment]
please reopen your pull request

use your forked repository
target of pull request should be 'develop' branch
link THIS pull request in the new one

**Pull request closed without merging**
