### PR TITLE
CATROID-1002 Add a Navigation Drawer

### PR DESCRIPTION
**Pull request by CodeWithSouma**
*CATROID-1002 Add a Navigation Drawer*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [✔️ ] Include the name of the Jira ticket in the PR’s title
- [✔️ ] Include a summary of the changes plus the relevant context
- [ ✔️] Choose the proper base branch (*develop*)
- [✔️ ] Confirm that the changes follow the project’s coding guidelines
- [ ✔️] Verify that the changes generate no compiler or linter warnings
- [ ✔️] Perform a self-review of the changes
- [ ✔️] Verify to commit no other files than the intentionally changed ones
- [ ✔️] Include reasonable and readable tests verifying the added or changed behavior
- [ ✔️] Confirm that new and existing unit tests pass locally
- [✔️ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ✔️] Stick to the project’s gitflow workflow
- [ ✔️] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

Giff
Pocket code navigation drawer

### CODE REVIEW

**Comment by CodeWithSouma** [comment]
@wslany sir, please review my PR

**Comment by CodeWithSouma** [comment]
@wslany sir, please review this PR

**Review by wslany — CHANGES_REQUESTED** [review]
Please squash to a single commit.

Please fix the lint warnings: https://jenkins.catrob.at/job/Catroid/job/PR-4066/1/analysis/

Please fix the ticket number: CATROID-999 is for a Bluetooth ticket, right?

Note that we have several flavors of our apps with different names, e.g., Embroidery Designer, and the name Pocket Code should therefore not appear in the strings.

Please add automatic tests.

**Comment by CodeWithSouma** [comment]
@wslany sir I don't know to fix the lint warnings please help me.

**Comment by juliajulie95** [comment]
Closed, as navigation drawers are not up to date with the current design guidelines.

**Pull request closed without merging**
