### PR TITLE
CATROID-668 Add Catrobat language test for exponent function

### PR DESCRIPTION
**Pull request by hofcle78**
Add Catrobat language test for exponent function

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by christophsiegl** [comment]
Tried to restart the CI tests several times, but there are RTL-, instrumented unit - and testrunner-tests which are always failing.
Maybe it is necessary to rebase your branch with the current upstream. Do not know what else could be the problem.
Please try this and check. (Similar problem like https://jira.catrob.at/browse/CATROID-651)

**Comment by hofcle78** [comment]
> Maybe it is necessary to rebase your branch with the current upstream.

Done, but the same tests are still failing on Jenkins.

**Review by christophsiegl — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Thanks. I've added two bricks to the attached test project as follows to indicate the relation to _e_ and make the expected level of precision explicit. 
image

Please replace with the attached test.
[testExponentFunction.zip](https://github.com/Catrobat/Catroid/files/5360703/testExponentFunction.zip)

**Comment by hofcle78** [comment]
Done.

**Review by christophsiegl — APPROVED** [review]

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
