### PR TITLE
Cat 1129 userbricks

### PR DESCRIPTION
**Pull request by sjaindl**
Reopened from #1719

### CODE REVIEW

**Comment by sjaindl** [comment]
Finishes the implementation of userbricks:

    Refactoring
    UX changes
    Lots of Bugfixing ;)
    Adds/fixes tests

I've also rebased on PR #1713 (first 2 commits), as removal of unpack and keep is relevant for userbricks, too. So, when this PR is merged, PR #1713 can be closed!

**Comment by sjaindl** [comment]
Full testrun down to 76 failures (from 82 in develop):
https://jenkins.catrob.at/view/LeeroyMultiJobs/job/CatroidEmulatorAllTestsSerialNightly/15/

@84n4n4: We further need to increase the timeout for uitest.content.interaction (There are many tests for the new userbrick backpack)..

**Comment by sjaindl** [comment]
n general this looks good to me, seems very robust.
I am not sure if I tested all the functionality.
I like that the big Methods got split up and everything is more readable now.
I'd like to have at least another person to look over this before merge as there are big changes.
please resolve the conflicts with the current develop branch.
for the tests: are the 76 failures the same as in develop or are there some new included?

**Comment by sjaindl** [comment]
Concerning tests,
Userbrick testrun: 
https://jenkins.catrob.at/view/LeeroyMultiJobs/job/CatroidEmulatorAllTestsSerialNightly/15/testReport/
Develop testrun:
https://jenkins.catrob.at/view/LeeroyMultiJobs/job/CatroidEmulatorAllTestsSerialNightly/16/testReport/

There are some tests that fail in develop but not in the userbricks branch and vice versa (a few of them seem a bit random to me). At least userbricks and backpack tests are working.

**Comment by sjaindl** [comment]
Out of curiosity, since I can't test it myself and the github docu doesn't state it very well.
@sjaindl, are you able to reopen this Pull Request now (before! you rebase)?

**Comment by sjaindl** [comment]
@robertpainsi I can't see an option to reopen the PR, neither before nor after rebasing (at least it seems that I don't have the permission to do so, if possible). Is it possible for you?

**Comment by sjaindl** [comment]
@sjaindl
Thank you for the info!

    Is it possible for you?

After a force push, no :smile_cat:

@thmq
Most developers (developers without write access) can't reopen their Pull Request once they are closed. So they have to create new ones. All previous code review comments, discussions and other information are located in older Pull Requests. So everything is scattered in multiple Pull Requests. :crying_cat_face:
Maybe adapt this?

**Comment by sjaindl** [comment]
+1 for @robertpainsi 
Would be nice to be able to reopen a PR.

**Comment by sjaindl** [comment]
ok to test

**Comment by sjaindl** [comment]
Here's the missing uitest.content.interaction testrun (timed out in whole testrun):
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidSinglePackageEmulatorTest/1887/

And the Catroid-Check testrun:
https://jenkins.catrob.at/view/LeeroyCatroid/job/CatroidCheck/220/

**Comment by thmq** [comment]
ok to test

**Pull request merged**
