### PR TITLE
ActionBarSherlock is replaced with ActionBarCompat

### PR DESCRIPTION
**Pull request by iboyko**
Build: https://jenkins.catrob.at/view/All-Categories/view/Catroid-multi-job/job/Catroid-Multi-Job-Custom-Branch-RELOADED/509/

appcompat lib v19.1.0 is used.

### CODE REVIEW

**Comment by avihric** [comment]
obsolete with #1162

**Comment by iboyko** [comment]
Cannot be obsolete on my opinion.
CAT-1242 says to use build level 16 but it says nothing about Action bar implementation. 
Replacing ActionBarSherlock with ActionBarCompat allows fast and native switch to Lollipop UI.

**Comment by aried3r** [comment]
I agree, we should use AppCompat instead.

Another question, can we delete `libraryProjects/` or is anything still using it?

**Comment by obusher** [comment]
With #1162 the targetVersion is increased to 21 so we could use `com.android.support:appcompat-v7:21+`. Was your testrun green ? It seems it got deleted already. :octocat:

**Comment by iboyko** [comment]
Pull request was created on Nov 11, 2014. It was not possible to get stable build at that time because of the problems with master branch. I have not started testrun after master became stable.

**Comment by iboyko** [comment]
@avihric What do you think about it?

**Comment by avihric** [comment]
Yes we can restore the branch and do a new PR on development branch. But first I want to process the other PRs before making new ones, except it is a critical bugfix.

**Comment by iboyko** [comment]
OK, I will create an Issue.

**Pull request closed without merging**
