### PR TITLE
CATROID-1237 REFACTOR SensorLoudness to Kotlin

### PR DESCRIPTION
**Pull request by Aayush2111**
jira ticket: https://jira.catrob.at/browse/CATROID-1237

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Aayush2111** [comment]
@devsebastian @sebastiangollob @mseiser 
Please review the changes and provide any feedback that you may have.
Thank you! :)

**Comment by sebastiangollob** [comment]
Please also assign the ticket to yourself and move it accordingly

**Comment by Aayush2111** [comment]
> Please also assign the ticket to yourself and move it accordingly

I don't have the options to assign and move tickets apparently, I guess someone from team will have to do it

**Review by sebastiangollob — APPROVED** [review]
lgtm

**Pull request closed without merging**
