### PR TITLE
Catroid-853 "Set rotation style" and incorrect collision contour for physics objects

### PR DESCRIPTION
**Pull request by bigsmallpp**
[Catroid-853 "Set rotation style" and incorrect collision contour for physics objects](https://jira.catrob.at/browse/CATROID-853)

Fixed several bugs that caused the rotation styles Dont-Rotate and Left-Right to not work properly.
Added an according Catrobat Language Test.

Several bugs that caused sprites to be displaced from their actual bounding-boxes when the rotation styles "Don't Rotate" or Left-Right Only" were applied to an object.

Please note, that the numbers for the asserts checking whether the object remains in bounds and matches the bounding-box were measured by hand (the max and min coordinates) plus/minus a buffer of 2 pixels outside of the screen-area in case an unexpected garbage collection or whatever happens and the x/y-coordinate gets offset by a tiny margin. 

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by NoQQ** [comment]
Please rebase to the current state of Catrobat

**Review by NoQQ — COMMENTED** [review]
Everything looks fine

**Review by NoQQ — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Hi, thanks! 

- There is still a lint warning that needs to be fixed, see jenkins build reports.
- Also the test is running for more than 10 seconds --- however there is a timeout for Catrobat language tests of 10000ms. Thus the CLT always fails on Jenkins:
image

Either the test has to be simplified, or separated into more than one test, each of less than 10 seconds. At that time, please also change the variable name in such a way that there is no abbreviation it it (underscore character followed by "DR"). Note that variables names in Catrobat are allowed to contain spaces, so there is no need to use an underscore character between words.

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
