### PR TITLE
[GSOC21] CATROID-1114 & CATROID-1115 & CATROID-1116

### PR DESCRIPTION
**Pull request by ndrnour**
CATROID-1114: [GSOC21] Room Integration 
CATROID-1115: [GSOC21] Save FeaturedProject locally
CATROID-1116: [GSOC21] Save ProjectResponse locally

extra changes:
update Kotlin version to 1.4.32
update Gson version to 2.8.7 

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by dandrawes — APPROVED** [review]
Well done!

**Comment by wslany** [comment]
I just tried with https://jenkins.catrob.at/job/Catroid/job/PR-4220/45/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-4220-45.apk (because until today the Web-API did not work, so I could not test the issue earlier), but unfortunately the same problem still occurs: the newest projects stay fixed, they never change after the first start. Even after a force stop and restart. At the same time, other PRs do not have this issue. Please, @ndrnour could you try again to fix this?

**Comment by ndrnour** [comment]
> I just tried with https://jenkins.catrob.at/job/Catroid/job/PR-4220/45/artifact/catroid/build/outputs/apk/catroid/debug/catroid-catroid-debug-PR-4220-45.apk (because until today the Web-API did not work, so I could not test the issue earlier), but unfortunately the same problem still occurs: the newest projects stay fixed, they never change after the first start. Even after a force stop and restart. At the same time, other PRs do not have this issue. Please, @ndrnour could you try again to fix this?

It's not a problem on my side, but on the Web-API side.
**short Explanation:**
The categories will be updated once the `X-Response-Hash` of GET request of this end-point `https://share.catrob.at/api/projects/categories` has been changed, which is not the case right now. It always has the value of `5df34577185a4d4a85f09cc48c5ee9cd`.
so please ask the catroweb team to fix that. (the `X-Response-Hash` must be re-generated once the categories changed.)

**Comment by wslany** [comment]
@ndrnour, @dmetzner fixed the hashes in https://github.com/Catrobat/Catroweb/pull/2264/commits/2e9cfa975f0666cdb3073bdae4e12d0e8095677e - now the newest project thumbnails are updated whenever the app is opened or reopened, but only then. I.e., no force close is needed anymore, but one nevertheless still needs to exit the app with the back button, then open it again, otherwise it will not refresh. So, this suggests to me that the hashes now correctly refresh, but it is only checked on entry. Shouldn't that be more often?

**Comment by ndrnour** [comment]
> @ndrnour, @dmetzner fixed the hashes in [Catrobat/Catroweb@2e9cfa9](https://github.com/Catrobat/Catroweb/commit/2e9cfa975f0666cdb3073bdae4e12d0e8095677e) - now the newest project thumbnails are updated whenever the app is opened or reopened, but only then. I.e., no force close is needed anymore, but one nevertheless still needs to exit the app with the back button, then open it again, otherwise it will not refresh. So, this suggests to me that the hashes now correctly refresh, but it is only checked on entry. Shouldn't that be more often?

should be fixed now.

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!!

**Pull request merged**
