### PR TITLE
CATROID-1078 Add new CLTs for the set transparency brick

### PR DESCRIPTION
**Pull request by reichli**
https://jira.catrob.at/browse/CATROID-1078

A new CLT was created to ensure proper test coverage of this brick. After the transparency of an object has been set it can be queried and checked via the `transparency`-property to make sure that it has been set correctly. Edge cases (what happens if the transparency goes beyond 100%/below 0%) have also been tested.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by adnaribo — APPROVED** [review]
Looks good.

**Review by wslany — CHANGES_REQUESTED** [review]
Please add test cases (in the same testSetTransparency.catrobat test suite) to check whether the transparency is actually changing on the screen. This can be done using the color sensors, and also the touch sensors, as well as the Tap bricks. There are several ways to do this. 

Please also add a test case (in the same testSetTransparency.catrobat test suite) that checks whether the brick is slowing down loops as expected (see https://jira.catrob.at/browse/CATROID-760 for details).

**Comment by wslany** [comment]
Please remember that the CLTs should be able to serve as a specification by example for future implementations and for Catty (which does not yet have a physics engine).

**Review by UlrichLa — APPROVED** [review]
Looks good!

**Review by mseiser — APPROVED** [review]

**Pull request merged**
