### PR TITLE
CATROID-21 Enable undo of formula editor edits

### PR DESCRIPTION
**Pull request by dandrawes**
https://jira.catrob.at/browse/CATROID-21
- copy code.xml to undo_code.xml and replacing it if undo is chosen
- save variables/lists and their values to restore after undo
- removed saving dialogs for formula editor
- show visual placement saving dialog only if there are changes
- added testcase

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Review by mstoeg — CHANGES_REQUESTED** [review]
Looks very good! Please fix the minor things I mentioned.

**Review by mstoeg — APPROVED** [review]

**Review by wslany — CHANGES_REQUESTED** [review]
Very nice. However:
* If you create a new variable or list in the formula editor in the data section using the floating + button, it is not shown and also later not created. Note that, before leaving the data section, the previously entered variable and list names (which are not visible) become unavailable, i.e., cannot be chosen again, and are marked with "this name is already in use, please chose another one." in red below the entry field, see screenshot below --- no "z" exists yet, but it cannot be chosen --- I attempted to create "z" before, but it is not visible, and later also not available.
image
* In the ticket, it was written that "When the UNDO button is pressed after the user scrolled up or down in the scripts so much that the brick is not on the screen anymore, the edits should be reverted as explained above and the edited brick should be put in the focus, i.e., the script view should be scrolled in such a way that the edited brick is situated at the top of the screen as far as possible, if there are enough other bricks to allow this." --- this works fine, but not always. E.g., if the brick is a "When __ becomes true" event brick, see below, after the undo this brick will be placed (it there are enough bricks below) just *above* the visible area, i.e., out of focus. 
image
=>
image

**Review by mstoeg — CHANGES_REQUESTED** [review]
Problems pointed out by @wslany were nicely solved. However I found another issue:
If I change something in one sprite, use the undo option immediately afterwards and then change the sprite, further changes are not "undoable" any more. (Have a look a the attached screencast)
https://user-images.githubusercontent.com/60399652/108956529-21c67100-7670-11eb-9f7a-22b0ec347156.mp4

**Comment by dandrawes** [comment]
> Problems pointed out by @wslany were nicely solved. However I found another issue:
> If I change something in one sprite, use the undo option immediately afterwards and then change the sprite, further changes are not "undoable" any more. (Have a look a the attached screencast)
> https://user-images.githubusercontent.com/60399652/108956529-21c67100-7670-11eb-9f7a-22b0ec347156.mp4

This problem was reported in the ticket [CATROID-927](https://jira.catrob.at/browse/CATROID-927) and affects all undo actions, therefore it is solved in a separate ticket.

**Review by mstoeg — APPROVED** [review]

**Review by wslany — APPROVED** [review]

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
