### PR TITLE
[REFACTORING] Refactored Dialogs for Accessibilty. Restore LoginIn fu…

### PR DESCRIPTION
**Pull request by thmq**
…nctionality

### CODE REVIEW

**Comment by 84n4n4** [comment]
test this please

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
@cheidenreich care to approve this pr?

**Comment by thmq** [comment]
test this please

**Comment by thmq** [comment]
please run espresso tests

**Comment by thmq** [comment]
please run espresso tests

**Pull request merged**
