### PR TITLE
CAT-2501 GSOC [TH] LoopBrickTests PhiroBrickTests UserListTests

### PR DESCRIPTION
**Pull request by 84n4n4**

### CODE REVIEW

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by thmq** [comment]
test this please

**Comment by 84n4n4** [comment]
ok to test

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
test this place

**Comment by 84n4n4** [comment]
test this please

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
please run espresso tests

**Pull request merged**
