### PR TITLE
CAT-2610 Fixes for sizes and visual glitches

### PR DESCRIPTION
**Pull request by FlorianWeissensteiner**
#CAT-2610
https://jira.catrob.at/browse/CAT-2610

### CODE REVIEW

**Comment by 84n4n4** [comment]
this breaks the rtl language picker ui test, please fix.

**Comment by 84n4n4** [comment]
please run espresso tests

**Comment by FlorianWeissensteiner** [comment]
please run espresso tests

**Comment by FlorianWeissensteiner** [comment]
I fixed the languageSettingsTest in SettingsActivityTest, assuming that is all I broke @84n4n4 ? It's a bit hard to tell which of the failed espresso tests is my fault, and which are just broken. But since the others don't seem to be related to any of my changes, I'm gonna assume it's just the one.

**Comment by FlorianWeissensteiner** [comment]
please run espresso tests

**Comment by 84n4n4** [comment]
looks good now

>> It's a bit hard to tell which of the failed espresso tests is my fault, and which are just broken.
this is exactly why im constantly pushing to get NOLB up to speed with the espresso tests.

**Pull request merged**
