### PR TITLE
CATROID-216 Save labels and inputs on user defined brick

### PR DESCRIPTION
**Pull request by mstoeg**
- Add a testcase for checking the equivalence of UserDefinedBricks
- Add a list into the sprite for storing UserDefinedBricks
- Adapt ToastUtils class to enable displaying colored toast messages
- Define a style in styles.xml for UserDefinedBricks

https://jira.catrob.at/browse/CATROID-216

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *catroid-stage* or *catroid-ide* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by mstoeg** [comment]
Thank you Wolfgang, you are absolutely right! As we discussed - if the user wants to create an empty brick this implicitly gets converted to a brick with an empty label in it. Unfortunately, as you noticed I forgot to do the equality check in this situation. The equality was only tested if the user explicitly created a brick with an empty label in it. I will fix it!

**Comment by wslany** [comment]
And one more change request: The distances between a label and an input field as well as between two input fields are slightly too small, and the vertical alignments also looks slightly different (I'm not sure though). Please make it look like in other bricks. See below for how it currently looks like, versus how it looks like in other bricks.
  
image

image

**Comment by wslany** [comment]
Note (added after my previous comment): I think the vertical alignment is actually correct, so no change needed there. Sorry!

**Comment by wslany** [comment]
Thanks!

**Pull request merged**
